In [2]:
from datasets import load_dataset, concatenate_datasets

dataset = load_dataset("theatticusproject/cuad-qa", revision="refs/convert/parquet")
train_data = dataset["train"]
test_data = dataset["test"]
print(len(train_data))
print(len(test_data))

/Users/aitbellalhamza/Desktop/RAG-for-contract-understanding-CUAD/.cuad-venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

22450
4182

In [3]:
full_data = concatenate_datasets([train_data, test_data])

In [4]:
seen_titles = set()
unique_contracts = []

for row in full_data:
    if row["title"] not in seen_titles:
        seen_titles.add(row["title"])
        unique_contracts.append({
            "title": row["title"],
            "context": row["context"]
        })
print(f"Number of unique contracts: {len(unique_contracts)}")

Number of unique contracts: 510

In [5]:
eval_examples = [{
    "title" : row["title"],
    "question": row["question"],
    "answers": row["answers"]["text"],
}
for row in full_data]

print(len(eval_examples))
print(eval_examples[0])

26632
{'title': 'LIMEENERGYCO_09_09_1999-EX-10-DISTRIBUTOR AGREEMENT', 'question': 'Highlight the parts (if any) of this contract related to "Document Name" that should be reviewed by a lawyer. Details: The name of the contract', 'answers': ['DISTRIBUTOR AGREEMENT']}

In [6]:
from collections import defaultdict

grouped = defaultdict(list)
for ex in eval_examples:
    key = (ex['title'], ex['question'])
    grouped[key].extend(ex['answers'])

eval_dataset_raw = [
    {"title": title, "question": question, "ground_truth": answers}
    for (title, question), answers in grouped.items() if len(answers)>0
]

print(f"Number of (contract, question) pairs with at least one answer: {len(eval_dataset_raw)}")

Number of (contract, question) pairs with at least one answer: 6702

In [7]:
import pandas as pd

def get_category(question):
    if '"' in question:
        return question.split('"')[1]
    return None

for item in eval_dataset_raw:
    item["category"]= get_category(item['question'])

by_category = defaultdict(list)
for item in eval_dataset_raw:
    by_category[item['category']].append(item)

rows= []
for category, items in by_category.items():
    lengths = [len(" ".join(it["ground_truth"])) for it in items]
    rows.append({
        "category": category,
        "n_examples": len(items),
        "avg_length_chars": sum(lengths)/len(lengths),
        "min_length_chars": min(lengths),
        "max_length_chars": max(lengths)
    })

summary_df = pd.DataFrame(rows).sort_values("avg_length_chars")
print(summary_df.to_string(index=False))

                          category  n_examples  avg_length_chars  min_length_chars  max_length_chars
                    Agreement Date         470         18.442553                 3               121
                     Document Name         510         30.482353                11               285
                    Effective Date         390         71.394872                 3               717
                           Parties         509        122.280943                17              1448
                     Governing Law         437        219.004577                42               885
                   Expiration Date         413        260.990315                12              1777
           Third Party Beneficiary          32        285.406250                64              1030
       Termination For Convenience         183        298.672131                35              2063
Notice Period To Terminate Renewal         111        337.279279               133              1277
                      Renewal Term         176        378.954545                66              3383
                   Anti-Assignment         374        513.350267                53              5118
           No-Solicit Of Customers          34        538.735294               122              2400
                Volume Restriction          82        571.695122                98              3155
           No-Solicit Of Employees          59        604.796610               180              1614
               Most Favored Nation          28        616.107143               147              1916
                Price Restrictions          15        666.266667               110              2941
                Uncapped Liability         111        681.162162               146              2816
               Covenant Not To Sue         100        686.820000                97              4188
                 Non-Disparagement          38        688.368421               142              3144
 Unlimited/All-You-Can-Eat-License          17        713.235294               144              2699
                Liquidated Damages          61        724.032787                70              3071
                 Warranty Duration          75        731.013333                81              3212
 Competitive Restriction Exception          76        743.710526               108              3000
                 Change Of Control         121        800.719008               128              5905
                       Exclusivity         180        824.700000                74              7125
                Joint Ip Ownership          46        849.434783                53              3634
                       Non-Compete         119        854.445378                81              7394
            Revenue/Profit Sharing         166        885.210843               107              4800
                Minimum Commitment         165        908.587879                29              8677
          Non-Transferable License         138        911.036232                42              8276
                  Cap On Liability         275        922.120000                39              7131
                      Audit Rights         214        933.350467                91              6655
           Ip Ownership Assignment         124       1042.701613                73              7233
                         Insurance         166       1077.680723                29              7295
        Affiliate License-Licensee          59       1082.677966                85              5763
         Post-Termination Services         182       1111.917582               103             15284
                     License Grant         255       1318.654902               124             11820
  Irrevocable Or Perpetual License          70       1335.028571               102              8286
                    Rofr/Rofo/Rofn          85       1703.505882                83             10297
        Affiliate License-Licensor          23       1851.826087               248              7086
                Source Code Escrow          13       2427.615385               250              8264

In [8]:
no_answer_dataset = [
    {"title": title, "question": question, "category": get_category(question)}
    for (title, question), answers in grouped.items() if len(answers)==0
]

print(f"Number of (contract, question) pairs with No answer (clause absent): {len(no_answer_dataset)}")

Number of (contract, question) pairs with No answer (clause absent): 14208

In [9]:
import random
random.seed(42)

N_POSITIVE_PER_CATEGORY = 5
N_NEGATIVE_PER_CATEGORY = 3

positive_sample = []
for category, items in by_category.items():
    n = min(N_POSITIVE_PER_CATEGORY, len(items))
    positive_sample.extend(random.sample(items, n))

print(f"positive sample size: {len(positive_sample)} (across {len(by_category)} categories)")

no_answer_by_category = defaultdict(list)
for item in no_answer_dataset:
    no_answer_by_category[item["category"]].append(item)

negative_sample = []
for category, items in no_answer_by_category.items():
    n = min(N_NEGATIVE_PER_CATEGORY, len(items))
    negative_sample.extend(random.sample(items, n))

print(f"negative sample size: {len(negative_sample)} (across {len(no_answer_by_category)} categories)")

positive sample size: 205 (across 41 categories)
negative sample size: 118 (across 40 categories)

In [10]:
positive_sample[0]

{'title': 'EmbarkComInc_19991008_S-1A_EX-10.10_6487661_EX-10.10_Co-Branding Agreement',
 'question': 'Highlight the parts (if any) of this contract related to "Document Name" that should be reviewed by a lawyer. Details: The name of the contract',
 'ground_truth': ['CO-BRANDING AGREEMENT'],
 'category': 'Document Name'}

In [11]:
import re

def clean_contract_text(text: str) -> str:

    text = re.sub(r"[ \t]{2,}", " ", text)

    text = re.sub(r"\n{3,}", "\n\n", text)

    text = "\n".join(line.strip() for line in text.split('\n'))

    return text.strip()

In [12]:
for c in unique_contracts:
    c["clean_context"] = clean_contract_text(c["context"])

In [13]:
for item in positive_sample:
    item["ground_truth_clean"] = [clean_contract_text(a) for a in item["ground_truth"]]

In [14]:
from llama_index.core import VectorStoreIndex, StorageContext
from llama_index.vector_stores.qdrant import QdrantVectorStore

def build_index_with_embedding(embed_model, nodes, collection_name, qdrant_client):
    vector_store = QdrantVectorStore(client = qdrant_client, collection_name=collection_name)
    storage_context = StorageContext.from_defaults(vector_store=vector_store)
    return VectorStoreIndex(nodes, storage_context=storage_context, embed_model=embed_model)

In [15]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("BAAI/bge-small-en-v1.5")

In [16]:
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core import Document
from collections import defaultdict

CHUNK_SIZE = 512
CHUNK_OVERLAP = 50

Splitter = SentenceSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    tokenizer=tokenizer.encode
)

documents = [
    Document(
        text=c["clean_context"], metadata={"title": c["title"]})
        for c in unique_contracts
]

nodes = Splitter.get_nodes_from_documents(documents)

# chunk index for each contract
counters = defaultdict(int)
for n in nodes:
    title = n.metadata["title"]
    n.metadata["chunk_index"] = counters[title]
    counters[title] += 1

print(f"Number of contracts : {len(documents)}")
print(f"Number of chunks: {len(nodes)}")
print(f"Average chunks per contract: {len(nodes)/len(documents):.1f}")

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (7558 > 512). Running this sequence through the model will result in indexing errors

Number of contracts : 510
Number of chunks: 14230
Average chunks per contract: 27.9

In [17]:
from qdrant_client import QdrantClient

client = QdrantClient(path="../artifacts/qdrant_storage")

In [22]:
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.embeddings.ollama import OllamaEmbedding

bge_large_embed = HuggingFaceEmbedding(model_name="BAAI/bge-large-en-v1.5")
index_bge_large = build_index_with_embedding(bge_large_embed, nodes, "cuad_bge_large", client)

nomic_embed = OllamaEmbedding(model_name="nomic-embed-text")
index_nomic = build_index_with_embedding(nomic_embed, nodes, "cuad_nomic", client)

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 6145.19it/s]

In [18]:
category_to_tier = {}

for _, row in summary_df.iterrows():
    if row["avg_length_chars"] < 150:
        tier = 1
    elif row['avg_length_chars'] < 900:
        tier = 2
    else:
        tier = 3
    
    category_to_tier[row['category']] = tier

print(category_to_tier)

{'Agreement Date': 1, 'Document Name': 1, 'Effective Date': 1, 'Parties': 1, 'Governing Law': 2, 'Expiration Date': 2, 'Third Party Beneficiary': 2, 'Termination For Convenience': 2, 'Notice Period To Terminate Renewal': 2, 'Renewal Term': 2, 'Anti-Assignment': 2, 'No-Solicit Of Customers': 2, 'Volume Restriction': 2, 'No-Solicit Of Employees': 2, 'Most Favored Nation': 2, 'Price Restrictions': 2, 'Uncapped Liability': 2, 'Covenant Not To Sue': 2, 'Non-Disparagement': 2, 'Unlimited/All-You-Can-Eat-License': 2, 'Liquidated Damages': 2, 'Warranty Duration': 2, 'Competitive Restriction Exception': 2, 'Change Of Control': 2, 'Exclusivity': 2, 'Joint Ip Ownership': 2, 'Non-Compete': 2, 'Revenue/Profit Sharing': 2, 'Minimum Commitment': 3, 'Non-Transferable License': 3, 'Cap On Liability': 3, 'Audit Rights': 3, 'Ip Ownership Assignment': 3, 'Insurance': 3, 'Affiliate License-Licensee': 3, 'Post-Termination Services': 3, 'License Grant': 3, 'Irrevocable Or Perpetual License': 3, 'Rofr/Rofo/Rofn': 3, 'Affiliate License-Licensor': 3, 'Source Code Escrow': 3}

In [19]:
category_to_tier["Agreement Date"] = 2
category_to_tier["Effective Date"] = 2

In [25]:
from llama_index.core.vector_stores import MetadataFilters, ExactMatchFilter

def retrieve_scoped_generic(title, question, category, index, top_k=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in nodes if n.metadata["title"] == title]

    if tier==1:
        contract_nodes = sorted(contract_nodes, key=lambda n:n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [n.get_content() for n in selected]
    
    filtered_retriever = index.as_retriever(
        similarity_top_k=top_k,
        filters = MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)
    return [n.get_content() for n in retrieved_nodes]

In [28]:
import re
import pandas as pd

def normalize_text(text):
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    text = text.strip()
    return text

def is_hit(reference_answers, retrieved_chunks):
    normalized_chunks = [normalize_text(chunk) for chunk in retrieved_chunks]
    for ref in reference_answers:
        normalized_ref = normalize_text(ref)
        if not normalized_ref:
            continue
        for chunk in normalized_chunks:
            if normalized_ref in chunk:
                return 1
        
    return 0

def compute_hit_rate(sample, index, top_k=3):
    results = []
    for item in sample:
        title = item["title"]
        question = item["question"]
        category = item["category"]
        reference_answers = item["ground_truth"]

        retrieved_chunks = retrieve_scoped_generic(title, question, category, index, top_k=top_k)
        hit = is_hit(reference_answers, retrieved_chunks)

        results.append({"title": title, "category": category, "question": question, "hit": hit})

    
    df_hits = pd.DataFrame(results)
    overall_hit_rate = df_hits["hit"].mean()
    hit_rate_by_category = df_hits.groupby("category")["hit"].mean().sort_values()
    return overall_hit_rate, hit_rate_by_category, df_hits

In [28]:
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
index_bge_small = build_index_with_embedding(embed_model, nodes, "cuad_bge_small", client)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5050.38it/s]

In [29]:
baseline_hit_rate, baseline_hit_vy_category, baseline_df = compute_hit_rate(positive_sample, index_bge_small)
print(f"Baseline (bge -small) hit rate: {baseline_hit_rate:.3f}")

bge_large_hit_rate, bge_large_hit_vy_category, bge_large_df = compute_hit_rate(positive_sample, index_bge_large)
print(f"Baseline (bge -large) hit rate: {bge_large_hit_rate:.3f}")

nomic_hit_rate, nomic_hit_vy_category, nomic_df = compute_hit_rate(positive_sample, index_nomic)
print(f"Baseline (nomic) hit rate: {nomic_hit_rate:.3f}")

Baseline (bge -small) hit rate: 0.498
Baseline (bge -large) hit rate: 0.546
Baseline (nomic) hit rate: 0.561

In [30]:
baseline_hit_vy_category

category
Unlimited/All-You-Can-Eat-License     0.0
Covenant Not To Sue                   0.0
Minimum Commitment                    0.2
Agreement Date                        0.2
Rofr/Rofo/Rofn                        0.2
Revenue/Profit Sharing                0.2
Post-Termination Services             0.2
Competitive Restriction Exception     0.2
Non-Transferable License              0.2
Non-Disparagement                     0.2
No-Solicit Of Customers               0.2
Irrevocable Or Perpetual License      0.2
Ip Ownership Assignment               0.2
Price Restrictions                    0.4
Most Favored Nation                   0.4
Volume Restriction                    0.4
Affiliate License-Licensee            0.4
Affiliate License-Licensor            0.4
Effective Date                        0.4
Joint Ip Ownership                    0.6
Uncapped Liability                    0.6
Third Party Beneficiary               0.6
Termination For Convenience           0.6
Audit Rights                          0.6
Renewal Term                          0.6
Warranty Duration                     0.6
Exclusivity                           0.6
Expiration Date                       0.6
Governing Law                         0.6
Liquidated Damages                    0.6
Non-Compete                           0.6
Notice Period To Terminate Renewal    0.8
Insurance                             0.8
Cap On Liability                      0.8
No-Solicit Of Employees               0.8
Anti-Assignment                       0.8
Source Code Escrow                    0.8
License Grant                         0.8
Document Name                         1.0
Change Of Control                     1.0
Parties                               1.0
Name: hit, dtype: float64

In [31]:
bge_large_hit_vy_category

category
Covenant Not To Sue                   0.0
Revenue/Profit Sharing                0.2
Non-Transferable License              0.2
Non-Disparagement                     0.2
No-Solicit Of Customers               0.2
Competitive Restriction Exception     0.2
Most Favored Nation                   0.2
Volume Restriction                    0.2
Affiliate License-Licensee            0.4
Unlimited/All-You-Can-Eat-License     0.4
Post-Termination Services             0.4
Liquidated Damages                    0.4
Irrevocable Or Perpetual License      0.4
Ip Ownership Assignment               0.4
Minimum Commitment                    0.4
Governing Law                         0.4
Affiliate License-Licensor            0.4
Agreement Date                        0.4
Effective Date                        0.4
Audit Rights                          0.6
Cap On Liability                      0.6
Non-Compete                           0.6
Warranty Duration                     0.6
Expiration Date                       0.6
Exclusivity                           0.6
License Grant                         0.6
Joint Ip Ownership                    0.6
No-Solicit Of Employees               0.8
Uncapped Liability                    0.8
Third Party Beneficiary               0.8
Termination For Convenience           0.8
Source Code Escrow                    0.8
Rofr/Rofo/Rofn                        0.8
Renewal Term                          0.8
Price Restrictions                    0.8
Anti-Assignment                       0.8
Insurance                             0.8
Change Of Control                     0.8
Parties                               1.0
Document Name                         1.0
Notice Period To Terminate Renewal    1.0
Name: hit, dtype: float64

In [32]:
nomic_hit_vy_category

category
Most Favored Nation                   0.0
Covenant Not To Sue                   0.0
Irrevocable Or Perpetual License      0.0
Affiliate License-Licensor            0.2
No-Solicit Of Customers               0.2
Volume Restriction                    0.2
Effective Date                        0.2
Affiliate License-Licensee            0.4
Revenue/Profit Sharing                0.4
Price Restrictions                    0.4
Non-Disparagement                     0.4
Non-Compete                           0.4
Liquidated Damages                    0.4
Ip Ownership Assignment               0.4
Minimum Commitment                    0.4
Warranty Duration                     0.4
Exclusivity                           0.4
Competitive Restriction Exception     0.4
Agreement Date                        0.4
Expiration Date                       0.6
Joint Ip Ownership                    0.6
License Grant                         0.6
Unlimited/All-You-Can-Eat-License     0.6
Audit Rights                          0.6
Non-Transferable License              0.6
Rofr/Rofo/Rofn                        0.6
Third Party Beneficiary               0.8
Termination For Convenience           0.8
Source Code Escrow                    0.8
Anti-Assignment                       0.8
Notice Period To Terminate Renewal    0.8
Insurance                             0.8
Cap On Liability                      0.8
No-Solicit Of Employees               0.8
Post-Termination Services             0.8
Renewal Term                          1.0
Parties                               1.0
Change Of Control                     1.0
Uncapped Liability                    1.0
Document Name                         1.0
Governing Law                         1.0
Name: hit, dtype: float64

In [33]:
merged = baseline_df[["title", "question", "category", "hit"]].rename(columns={"hit": "hit_bge_small"})
merged = merged.merge(
    bge_large_df[["title", "question", "hit"]].rename(columns={"hit": "hit_bge_large"}),
    on=["title", "question"]
)
merged = merged.merge(
    nomic_df[["title", "question", "hit"]].rename(columns={"hit": "hit_nomic"}),
    on=["title", "question"]
)

merged["n_hits"] = merged[["hit_bge_small", "hit_bge_large", "hit_nomic"]].sum(axis=1)

persistent_miss = (merged["n_hits"] == 0).mean()
persistent_hit = (merged["n_hits"] == 3).mean()
mixed = ((merged["n_hits"] > 0) & (merged["n_hits"] < 3)).mean()

print(f"Echec avec les 3 modeles (probleme structurel, pas l'embedding) : {persistent_miss:.1%}")
print(f"Succes avec les 3 modeles : {persistent_hit:.1%}")
print(f"Resultat mixte (sensible au choix du modele) : {mixed:.1%}")

Echec avec les 3 modeles (probleme structurel, pas l'embedding) : 30.7%
Succes avec les 3 modeles : 37.1%
Resultat mixte (sensible au choix du modele) : 32.2%

In [36]:
e5_embed = HuggingFaceEmbedding(
    model_name="intfloat/e5-large-v2",
    query_instruction="query: ",
    text_instruction="passage: ",
    embed_batch_size=256)

index_e5 = build_index_with_embedding(e5_embed, nodes, "cuad_e5_large", client)

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 4017.72it/s]

In [37]:
e5_hit_rate, e5_hit_by_category, e5_df = compute_hit_rate(positive_sample, index_e5)
print(f"e5-large-v2 hit rate: {e5_hit_rate:.3f}")

e5-large-v2 hit rate: 0.541

In [38]:
import random

failure_pool = merged[(merged["n_hits"] == 0) & (~merged["category"].isin(["Document Name", "Parties"]))]

random.seed(123)
sample_indices = random.sample(list(failure_pool.index), 10)
inspection_sample = failure_pool.loc[sample_indices]

positive_lookup = {(item["title"], item["question"]): item for item in positive_sample}

In [42]:
inspection_sample

,title,question,category,hit_bge_small,hit_bge_large,hit_nomic,n_hits
18,ChinaRealEstateInformationCorp_20090929_F-1_EX...,Highlight the parts (if any) of this contract ...,Effective Date,0,0,0,0
69,"Array BioPharma Inc. - LICENSE, DEVELOPMENT AN...",Highlight the parts (if any) of this contract ...,Minimum Commitment,0,0,0,0
21,"Magenta Therapeutics, Inc. - Master Developmen...",Highlight the parts (if any) of this contract ...,Expiration Date,0,0,0,0
169,"Sonos, Inc. - Manufacturing Agreement",Highlight the parts (if any) of this contract ...,Non-Transferable License,0,0,0,0
94,ReedsInc_20191113_10-Q_EX-10.4_11888303_EX-10....,Highlight the parts (if any) of this contract ...,Covenant Not To Sue,0,0,0,0
202,PapaJohnsInternationalInc_20190617_8-K_EX-10.1...,Highlight the parts (if any) of this contract ...,Non-Disparagement,0,0,0,0
22,GOCALLINC_03_30_2000-EX-10.7-Promotion Agreement,Highlight the parts (if any) of this contract ...,Expiration Date,0,0,0,0
179,TheglobeComInc_19990503_S-1A_EX-10.20_5416126_...,Highlight the parts (if any) of this contract ...,Most Favored Nation,0,0,0,0
17,GLOBALTECHNOLOGIESLTD_06_08_2020-EX-10.16-CONS...,Highlight the parts (if any) of this contract ...,Effective Date,0,0,0,0
92,PHLVARIABLEINSURANCECOCT_08_17_2009-EX-10.1-ST...,Highlight the parts (if any) of this contract ...,Covenant Not To Sue,0,0,0,0

In [43]:
for _, row in inspection_sample.iterrows():
    title = row["title"]
    question = row["question"]
    category = row["category"]
    item = positive_lookup[(title, question)]
    ground_truth = item["ground_truth"]

    retrieved_chunks = retrieve_scoped_generic(title, question, category, index_nomic, top_k=3)

    print("=" * 100)
    print(f"Categorie: {category}")
    print(f"Question: {question}")
    print(f"Ground truth: {ground_truth}")
    print("-" * 100)
    for i, chunk in enumerate(retrieved_chunks):
        print(f"[Chunk {i}]\n{chunk}\n")

====================================================================================================
Categorie: Effective Date
Question: Highlight the parts (if any) of this contract related to "Effective Date" that should be reviewed by a lawyer. Details: The date when the contract is effective
Ground truth: ['"Effective Date" means the Closing Date as set forth in the Share Purchase Agreement.']
----------------------------------------------------------------------------------------------------
[Chunk 0]
ARTICLE VI TERM AND TERMINATION

6.1. Term. The initial term of this Agreement (the "Initial Term") shall commence on the Effective Date and shall continue for a period of ten (10) years thereafter. Beginning twelve (12) months prior to the expiration of the Initial Term, the Parties shall use

7

Source: CHINA REAL ESTATE INFORMATION CORP, F-1, 9/29/2009

good faith efforts to negotiate an extension of the term of this Agreement (the Initial Term together with any applicable extension, the "Term").

6.2. Termination for Bankruptcy. Either Party may immediately terminate this Agreement in the event that the other Party (a) becomes insolvent or unable to pay its debts as they mature; (b) makes an assignment for the benefit of its creditors; (c) seeks relief, or if proceedings are commenced against such other Party or on its behalf, under any bankruptcy, insolvency or debtors' relief law and such proceedings have not been vacated or set aside within seven (7) days from the date of commencement thereof.

6.3. Termination for Breach.

(a) By Licensor. Licensor may terminate this Agreement at any time in the event that the Licensee is in material default or breach of any provision of this Agreement, and, if such default or breach is capable of cure, such default or breach continues uncured for a period of thirty (30) days after receipt of written notice thereof; provided, however, that in the event that the Licensee has in good faith commenced cure within such thirty (30) day period, but cannot practically complete such cure within such thirty (30) day period, the Parties shall negotiate a reasonable additional time to cure.

(b) By Licensee.

[Chunk 1]
10.13. No Presumption. The Parties acknowledge that each has been represented by counsel in connection with this Agreement and the transactions contemplated by this Agreement. Accordingly, any applicable Law that would require interpretation of any claimed

14

Source: CHINA REAL ESTATE INFORMATION CORP, F-1, 9/29/2009

ambiguities in this Agreement against the Party that drafted it has no application and is expressly waived. If any claim is made by a Party relating to any conflict, omission or ambiguity in the provisions of this Agreement, no presumption or burden of proof or persuasion will be implied because this Agreement was prepared by or at the request of any Party or its counsel.

10.14. Specific Performance. The parties hereto acknowledge and agree that irreparable damage would occur if any of the provisions of this Agreement are not performed in accordance with their specific terms and that any breach of this Agreement could not be adequately compensated in all cases by monetary damages alone. Accordingly, in addition to any other right or remedy to which a party hereto may be entitled, at law or in equity, it shall be entitled to enforce any provision of this Agreement by a decree of specific performance and to temporary, preliminary and permanent injunctive relief to prevent breaches or threatened breaches of any of the provisions of this Agreement, without posting any bond or other undertaking.

10.15. Force Majeure. Neither Party shall be liable for failure to perform any of its obligations under this Agreement during any period in which such Party cannot perform due to hacker attack, fire, flood or other natural disaster, war, embargo, riot or the intervention of any Governmental Authority, provided, however, that the Party so delayed immediately notifies the other Party of such delay. In no event shall such nonperformance by Licensee be excused due to any such event for longer than ninety (90) days.

10.16. Counterparts.

[Chunk 2]
(b) By Licensee. Licensee may terminate this Agreement at any time in the event that the Licensor is in material default or breach of any provision of this Agreement, and, if such default or breach is capable of cure, such default or breach continues uncured for a period of thirty (30) days after receipt of written notice thereof; provided, however, that in the event that the Licensor has in good faith commenced cure within such thirty (30) day period, but cannot practically complete such cure within such thirty (30) day period, the Parties shall negotiate a reasonable additional time to cure.

6.4. Termination for a Change of Control. Licensor may terminate this Agreement by providing prior written notice to Licensee upon the occurrence of a Change of Control.

6.5. Termination in the Event of Termination of Agency Agreement. In the event that the Agency Agreement is terminated pursuant to Section 9.02 (c)(iii) or 9.02(d)(i) thereof, this Agreement shall automatically be terminated as of the effective date of the termination of the Agency Agreement and shall thereafter be of no further force or effect except as set forth in Section 6.7.

6.6. Effect of Termination.

(a) Upon termination (but not expiration) of this Agreement for any reason, Licensee shall be entitled to use the Licensed Domain Names and Licensed Content for a limited period of time, not to exceed ninety (90) days, during which it shall diligently work to transition to another solution. Upon expiration of this Agreement or such 90-day period, (i) all rights granted to Licensee under this Agreement with respect to the Licensed Domain Names and Licensed Content shall immediately cease, and (ii) Licensee shall immediately discontinue all use of the Licensed Domain Names and Licensed Content.

====================================================================================================
Categorie: Minimum Commitment
Question: Highlight the parts (if any) of this contract related to "Minimum Commitment" that should be reviewed by a lawyer. Details: Is there a minimum order size or minimum amount or units per-time period that one party must buy from the counterparty under the contract?
Ground truth: ['Notwithstanding Sections 6.4, 6.5, and 6.6, the Royalty Payment to Array shall not be reduced in any calendar quarter (a) during the Initial Royalty Term to less than [ * ] of the amount due under Section 6.3(a)(i), and (b) during the Secondary Royalty Term to less than [ * ] of the amount due under Section 6.3(a) (ii) (provided that any amounts in excess of the permitted deduction shall be carried forward to the subsequent calendar quarters until exhausted), unless 6.4(b) applies in which case royalty shall be as set forth therein.']
----------------------------------------------------------------------------------------------------
[Chunk 0]
The request shall indicate the grounds on which it is based. The Parties shall then consult one another with a view to revising the contract an equitable basis, in order to ensure that neither Party suffers excessive prejudice. The request for revision does not of itself suspend performance of the contract. If the Parties fail to agree on the revision of the contract within time limit of ninety (90) business days of the request, the contract remains in force in accordance with its original terms.

18.3 Governing Law. This Agreement and all questions regarding its validity or interpretation, or the breach or performance of this Agreement, shall be governed by, and construed and enforced in accordance with, the laws of the State of New York, United States, without reference to conflict of law principles. The Parties hereby agree that the provisions of the United Nations Convention on Contracts for the International Sale of Goods shall not apply to this Agreement and are strictly excluded.

18.4 Waiver of Breach. The failure of either Party at any time or times to require performance of any provision hereof shall in no manner affect its rights at a later time to enforce the same. No waiver by either Party of any condition or term in any one or more instances shall be construed as a further or continuing waiver of such condition or term or of another condition or term.

18.5 Modification. No amendment or modification of any provision of this Agreement shall be effective unless in writing signed by both Parties hereto. No provision of this Agreement shall be varied, contradicted or explained by any oral agreement, course of dealing or performance or any other matter not set forth in an agreement in writing and signed by both Parties hereto.

18.6 Severability. In the event any provision of this Agreement should be held invalid, illegal, or unenforceable in any jurisdiction, the Parties shall negotiate in good faith a valid, legal and enforceable substitute provision that most nearly reflects the original intent of the Parties and all other provisions of this Agreement shall remain in full force and effect in such jurisdiction.

[Chunk 1]
For clarity, the forgoing supply obligations not apply to materials that are generally commercially available.

9.3 Clinical Supply. The Parties shall establish as soon as practicable following the Effective Date procedures for the supply of Materials to Ono for use in performing Ono's Development activities under Development Plan and any Joint Development Plans that may subsequently be agreed to by the Parties, and the Parties shall enter into a clinical supply agreement and quality agreement within three (3) months of the Effective Date pursuant to which:

(a) Array shall procure Materials on behalf of and as reasonably requested in writing by Ono, which Materials will be supplied to Ono at transfer price equal to: (i) Array's manufacturing cost to the extent that Array or its Affiliate(s) Manufacture such Materials itself, or (ii) the purchase price paid by Array for such Materials to the extent that Array elects to have such Materials Manufactured by a Subcontractor. The clinical supply agreement shall contain forecasting and ordering procedures (including lead times), product specifications, delivery terms and other customary terms, which terms shall in all cases be consistent with Array's contractual arrangements with its Subcontractors;

(b) Array may place orders for Materials with its Subcontractors on Ono's behalf, or, subject to Ono and the Subcontractors entering into an agreement or other arrangement therefor, Array shall arrange with such Subcontractors for Ono to place such orders, for shipment to Ono and for Ono to pay for such Materials directly to the particular supplier. Array shall not require Ono to place orders directly with a Subcontractor if such Subcontractor is unwilling to fulfill such orders on terms as favorable to Ono as the terms such Subcontractors have extended to Array.

(c) Array shall use Diligent Efforts to secure for Ono the inspection rights from Array's Subcontractors for Materials. In the event Array is unable to secure such inspection rights from any of its Subcontractors, Array agrees to secure such rights for itself and, if requested by Ono, Array

49

[ * ] = Certain confidential information contained in this document, marked by brackets, has been omitted and filed separately with the Securities and Exchange Commission pursuant to Rule 24b-2 of the Securities Exchange Act of 1934, as amended.

[Chunk 2]
(g) Interim Relief. The Arbitration Tribunal shall have the power to grant any remedy or relief that it deems appropriate, whether provisional or final, including but not limited to conservatory relief and injunctive relief, and any such measures ordered by the Arbitration Tribunal shall, notwithstanding anything to the contrary in the governing law selected by the Parties pursuant to Section 18.3, be deemed to be a final award on the subject matter of the measures and shall be enforceable as such. Each Party retains the right to apply to any court of competent jurisdiction for provisional and/or conservatory relief, including injunctions or temporary restraining orders before or after the constitution of the Arbitration Tribunal, and any such request shall not be deemed incompatible with the Agreement to arbitrate or a waiver of the right to arbitrate.

ARTICLE XVIII

GENERAL PROVISIONS

18.1 Force Majeure. If the performance of any part of this Agreement (except for any payment obligation under this Agreement) by either Party is prevented, restricted, interfered with or delayed by

80

[ * ] = Certain confidential information contained in this document, marked by brackets, has been omitted and filed separately with the Securities and Exchange Commission pursuant to Rule 24b-2 of the Securities Exchange Act of 1934, as amended.

reason of any cause beyond the reasonable control of such Party (including, fire, flood, earthquake, tsunami, embargo, power shortage or failure, acts of war, insurrection, riot, terrorism, strike, lockout or other labor disturbance, acts of God or any acts, omissions or delays in acting of the other Party), the Party so affected shall, upon giving written notice to the other Party, be excused from such performance to the extent of such prevention, restriction, interference or delay; provided that the affected Party shall use its reasonable efforts to avoid or remove such causes of non-performance and shall continue performance with the utmost dispatch whenever such causes are removed.

18.2 Hardship. Should the occurrence of events not contemplated by the Parties fundamentally after the equilibrium of the present contract thereby placing an excessive burden on one of the Parties in the performance of its contractual obligations, that Party may proceed as follows: The party shall make a request for revision within a reasonable time from the moment it become aware of the event and of its effect on the economy of the present contract.

====================================================================================================
Categorie: Expiration Date
Question: Highlight the parts (if any) of this contract related to "Expiration Date" that should be reviewed by a lawyer. Details: On what date will the contract's initial term expire?
Ground truth: ['This Agreement shall commence on the Effective Date and shall extend for a period of Five (5) years thereafter ("Initial Term"), unless this Agreement is terminated earlier as provided herein or is extended by mutual written agreement of the Parties.']
----------------------------------------------------------------------------------------------------
[Chunk 0]
This Agreement may be renewed for additional periods of one (1) year (each such additional period, a "Renewal Term") unless either Party provides notice of nonrenewal upon not less than [***] prior written notice to the other Party. Notwithstanding the foregoing, each Project Plan may have separate term and termination provisions, so long as the term of any Project Plan does not extend beyond the Initial Term or a subsequent Renewal Term.

7.2 Termination. This Agreement or any Project Plan may be terminated:

(a) by Magenta for any reason upon [***] written notice to Bachem;

(b) by either Party if the other Party materially breaches a provision of this Agreement or a Project Plan, and fails to cure such breach within [***] following receipt of written notification of such breach from the non-breaching Party;

(c) by either Party, immediately, if the other Party becomes insolvent, is dissolved or liquidated, makes a general assignment for the benefit of its creditors, or files or has filed against it, a petition in bankruptcy that is not dismissed within sixty days after filing, or has a receiver appointed for a substantial part of its assets; and

(d) by a Party or the Parties pursuant to Section 13.

In the event of termination pursuant to Section 7.2(a) or a termination by Bachem pursuant to Section 7.2(b), Bachem shall be compensated for Services rendered up to the date of termination. In the event of any other termination, the Parties shall negotiate in good faith to determine the appropriate amount to be paid by Magenta to Bachem (or refunded to Magenta by Bachem, as the case may be), in light of the circumstances of such termination, in compensation for all Services rendered in accordance with this Agreement. In the event of Bachem's inability to supply the Product or a material breach by Bachem pursuant to Section 7.2(b), Bachem shall provide, without additional charge to Magenta, sufficient information and technology pertaining to its Services to Magenta and/or its technically competent designee, such that Magenta and/or its technically competent designee are enabled to continue Development Work and manufacture of the Product.

[Chunk 1]
If this Agreement is terminated by Magenta pursuant to Section 7.2(a) or by Bachem pursuant to Section 7.2(b) or (c), Magenta shall also pay to Bachem amounts for any services that cannot be reasonably stopped at the time of termination; provided, that, Bachem will take all reasonable steps necessary to wind down such work as promptly as practicable.

7.5 Survival. The rights and obligations of each Party which by their nature survive the termination or expiration of this Agreement shall survive the termination or expiration of this Agreement, including Sections 4.2, 5, 6.3-6.6, 7.2-7.5, 8, 9, 10, 11, 12, 14, 15.1, 15.4-15.8, 15.10, 15.11 and 15.12. In addition, Bachem hereby acknowledges that neither expiration nor termination of this Agreement shall affect in any manner Magenta's right to manufacture and sell, or have manufactured and sold, the Product.

Section 8. INTELLECTUAL PROPERTY

8.1 Magenta Pre-Existing Intellectual Property. All intellectual property (including trademarks), including all data, information, know-how, reports and any and all related documentation, which are developed, generated or derived, directly or indirectly by or on behalf of Magenta prior to the Effective Date ("Magenta Pre-Existing Intellectual Property") shall remain the sole property of Magenta.

8.2 Bachem Intellectual Property. All intellectual property (including trademarks), including all data, information, reports, manufacturing know- how and any and all related documentation, which are (a) developed, generated or derived, directly or indirectly by or on behalf of Bachem prior to the Effective Date or (b) any manufacturing know-how developed or generated by Bachem that is generally applicable to the field of peptide manufacturing and not specific to the Product or Magenta's Confidential Information (such items under the foregoing clauses (a) and (b), collectively, "Bachem Intellectual Property"), shall remain the sole property of Bachem. In the event that any Bachem Intellectual Property is incorporated into any 12

CONFIDENTIAL TREATMENT REQUESTED.

[Chunk 2]
The termination of any Project Plan may be independent of the termination of this Agreement. 11


In [45]:
vector_store_hybrid = QdrantVectorStore(
    collection_name = "cuad_nomic_bm25_hybrid",
    client = client,
    enable_hybrid = True,
    fastembed_sparse_model = "Qdrant/bm25"
)
storage_context_hybrid = StorageContext.from_defaults(vector_store=vector_store_hybrid)
index_hybrid = VectorStoreIndex(nodes, storage_context=storage_context_hybrid, embed_model=nomic_embed)

In [47]:
def retrieve_scoped_hybrid(title, question, category, index, top_k=3, sparse_top_k=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n:n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [n.get_content() for n in selected]
    
    filtered_retriever = index.as_retriever(
        similarity_top_k=top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)
    return [n.get_content() for n in retrieved_nodes]

In [48]:
def compute_hit_rate(sample, index, retrieve_fn=retrieve_scoped_generic, top_k=3):
    results = []
    for item in sample:
        title = item["title"]
        question = item["question"]
        category = item["category"]
        reference_answers = item["ground_truth"]

        retrieved_chunks = retrieve_fn(title, question, category, index, top_k=top_k)
        hit = is_hit(reference_answers, retrieved_chunks)

        results.append({"title": title, "category": category, "question": question, "hit": hit})

    
    df_hits = pd.DataFrame(results)
    overall_hit_rate = df_hits["hit"].mean()
    hit_rate_by_category = df_hits.groupby("category")["hit"].mean().sort_values()
    return overall_hit_rate, hit_rate_by_category, df_hits

In [49]:
hybrid_hit_rate, hybrid_hit_by_category, hybrid_df = compute_hit_rate(
    positive_sample, index_hybrid, retrieve_fn=retrieve_scoped_hybrid)
print(f"Hybrid (nomic + BM25) hit rate: {hybrid_hit_rate:.3f}")

Hybrid (nomic + BM25) hit rate: 0.610

In [52]:
hybrid_hit_by_category

category
Effective Date                        0.0
Minimum Commitment                    0.2
Revenue/Profit Sharing                0.2
Most Favored Nation                   0.2
Volume Restriction                    0.2
Competitive Restriction Exception     0.2
Covenant Not To Sue                   0.2
Exclusivity                           0.2
Price Restrictions                    0.4
Non-Disparagement                     0.4
Non-Compete                           0.4
Liquidated Damages                    0.4
Irrevocable Or Perpetual License      0.4
Ip Ownership Assignment               0.4
Warranty Duration                     0.4
Affiliate License-Licensor            0.4
Agreement Date                        0.4
Affiliate License-Licensee            0.6
Joint Ip Ownership                    0.6
Termination For Convenience           0.6
Cap On Liability                      0.6
No-Solicit Of Customers               0.6
Rofr/Rofo/Rofn                        0.6
Non-Transferable License              0.6
Unlimited/All-You-Can-Eat-License     0.8
Uncapped Liability                    0.8
Source Code Escrow                    0.8
Audit Rights                          0.8
Insurance                             0.8
Post-Termination Services             0.8
Third Party Beneficiary               1.0
Governing Law                         1.0
Parties                               1.0
Anti-Assignment                       1.0
No-Solicit Of Employees               1.0
Change Of Control                     1.0
Document Name                         1.0
License Grant                         1.0
Expiration Date                       1.0
Renewal Term                          1.0
Notice Period To Terminate Renewal    1.0
Name: hit, dtype: float64

In [56]:
from llama_index.core.postprocessor import SentenceTransformerRerank

reranker = SentenceTransformerRerank(
    model = "BAAI/bge-reranker-base",
    top_n = 3
)

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 9949.43it/s]

In [25]:
def retrieve_scoped_reranked(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.get_content(), "score": None} for n in selected]

    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)

    reranker.top_n = rerank_top_n
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=question)

    return [{"text": n.get_content(), "score": n.score} for n in reranked_nodes]

In [26]:
def compute_hit_rate_reranked(sample, index, retrieve_fn=retrieve_scoped_reranked, rerank_top_n=3):
    results = []
    for item in sample:
        title = item["title"]
        question = item["question"]
        category = item["category"]
        reference_answers = item["ground_truth"]

        retrieved = retrieve_fn(title, question, category, index, rerank_top_n=rerank_top_n)
        retrieved_texts = [r["text"] for r in retrieved]
        retrieved_scores = [r["score"] for r in retrieved]

        hit = is_hit(reference_answers, retrieved_texts)

        results.append({
            "title": title,
            "category": category,
            "question": question,
            "hit": hit,
            "retrieved_chunks": retrieved_texts,
            "retrieved_scores": retrieved_scores,
        })

    df_hits = pd.DataFrame(results)
    overall_hit_rate = df_hits["hit"].mean()
    hit_rate_by_category = df_hits.groupby("category")["hit"].mean().sort_values()
    return overall_hit_rate, hit_rate_by_category, df_hits

In [64]:
reranked_hit_rate, reranked_hit_by_category, reranked_df = compute_hit_rate_reranked(
    positive_sample, index_hybrid
)
print(f"Hybrid + reranking hit rate: {reranked_hit_rate:.3f}")

Hybrid + reranking hit rate: 0.585

In [65]:
reranked_hit_by_category

category
Minimum Commitment                    0.0
Agreement Date                        0.0
Most Favored Nation                   0.0
Rofr/Rofo/Rofn                        0.0
Revenue/Profit Sharing                0.0
Ip Ownership Assignment               0.2
No-Solicit Of Customers               0.2
Competitive Restriction Exception     0.2
Volume Restriction                    0.2
Expiration Date                       0.4
Covenant Not To Sue                   0.4
Price Restrictions                    0.4
Liquidated Damages                    0.4
Non-Compete                           0.6
Non-Transferable License              0.6
Termination For Convenience           0.6
Uncapped Liability                    0.6
Non-Disparagement                     0.6
Warranty Duration                     0.6
Joint Ip Ownership                    0.6
Exclusivity                           0.6
Effective Date                        0.6
Audit Rights                          0.6
License Grant                         0.6
Unlimited/All-You-Can-Eat-License     0.8
Affiliate License-Licensor            0.8
Third Party Beneficiary               0.8
Source Code Escrow                    0.8
Cap On Liability                      0.8
Post-Termination Services             0.8
No-Solicit Of Employees               0.8
Insurance                             0.8
Irrevocable Or Perpetual License      0.8
Affiliate License-Licensee            0.8
Change Of Control                     1.0
Renewal Term                          1.0
Notice Period To Terminate Renewal    1.0
Document Name                         1.0
Anti-Assignment                       1.0
Governing Law                         1.0
Parties                               1.0
Name: hit, dtype: float64

In [66]:
reranked_merged = hybrid_df[["title", "question", "category", "hit"]].rename(columns={"hit": "hit_hybrid"})
reranked_merged = reranked_merged.merge(
    reranked_df[["title", "question", "hit"]].rename(columns={"hit": "hit_reranked"}),
    on=["title", "question"]
)

regressions = reranked_merged[(reranked_merged["hit_hybrid"] == 1) & (reranked_merged["hit_reranked"] == 0)]
print(f"Nombre de regressions (hit avec hybride seul, miss apres reranking) : {len(regressions)}")
regressions

Nombre de regressions (hit avec hybride seul, miss apres reranking) : 21

,title,question,category,hit_hybrid,hit_reranked
10,"VNUE,INC_07_10_2015-EX-10.1-SPONSORSHIP AGREEMENT",Highlight the parts (if any) of this contract ...,Agreement Date,1,0
12,LOOKSMARTLTD_07_20_2012-EX-99.(D)(I)-SPONSORSH...,Highlight the parts (if any) of this contract ...,Agreement Date,1,0
21,"Magenta Therapeutics, Inc. - Master Developmen...",Highlight the parts (if any) of this contract ...,Expiration Date,1,0
22,GOCALLINC_03_30_2000-EX-10.7-Promotion Agreement,Highlight the parts (if any) of this contract ...,Expiration Date,1,0
23,"VNUE,INC_07_10_2015-EX-10.1-SPONSORSHIP AGREEMENT",Highlight the parts (if any) of this contract ...,Expiration Date,1,0
43,"Loop Industries, Inc. - Marketing Agreement",Highlight the parts (if any) of this contract ...,No-Solicit Of Customers,1,0
44,WPPPLC_04_30_2020-EX-4.28-SERVICE AGREEMENT,Highlight the parts (if any) of this contract ...,No-Solicit Of Customers,1,0
46,BUFFALOWILDWINGSINC_06_05_1998-EX-10.3-FRANCHI...,Highlight the parts (if any) of this contract ...,No-Solicit Of Employees,1,0
50,STAMPSCOMINC_06_24_1999-EX-10.18-SPONSORSHIP A...,Highlight the parts (if any) of this contract ...,Rofr/Rofo/Rofn,1,0
51,PhoenixNewMediaLtd_20110421_F-1_EX-10.17_69583...,Highlight the parts (if any) of this contract ...,Rofr/Rofo/Rofn,1,0
54,LiquidmetalTechnologiesInc_20200205_8-K_EX-10....,Highlight the parts (if any) of this contract ...,Rofr/Rofo/Rofn,1,0
67,MEDIWOUNDLTD_01_15_2014-EX-10.6-SUPPLY AGREEMENT,Highlight the parts (if any) of this contract ...,Minimum Commitment,1,0
71,PareteumCorp_20081001_8-K_EX-99.1_2654808_EX-9...,Highlight the parts (if any) of this contract ...,License Grant,1,0
72,INGEVITYCORP_05_16_2016-EX-10.5-INTELLECTUAL P...,Highlight the parts (if any) of this contract ...,License Grant,1,0
104,Apollo Endosurgery - Manufacturing and Supply ...,Highlight the parts (if any) of this contract ...,Audit Rights,1,0
106,DovaPharmaceuticalsInc_20181108_10-Q_EX-10.2_1...,Highlight the parts (if any) of this contract ...,Uncapped Liability,1,0
136,"SightLife Surgical, Inc. - STRATEGIC SALES _ M...",Highlight the parts (if any) of this contract ...,Ip Ownership Assignment,1,0
157,"SightLife Surgical, Inc. - STRATEGIC SALES _ M...",Highlight the parts (if any) of this contract ...,Revenue/Profit Sharing,1,0
163,"SUCAMPOPHARMACEUTICALS,INC_11_04_2015-EX-10.2-...",Highlight the parts (if any) of this contract ...,Third Party Beneficiary,1,0
168,GridironBionutrientsInc_20171206_8-K_EX-10.1_1...,Highlight the parts (if any) of this contract ...,Non-Transferable License,1,0
179,TheglobeComInc_19990503_S-1A_EX-10.20_5416126_...,Highlight the parts (if any) of this contract ...,Most Favored Nation,1,0

In [67]:
for _, row in regressions.head(5).iterrows():
    title = row["title"]
    question = row["question"]
    category = row["category"]
    item = positive_lookup[(title, question)]
    ground_truth = item["ground_truth"]

    pool_10 = retrieve_scoped_hybrid(title, question, category, index_hybrid, top_k=10, sparse_top_k=10)
    gt_in_pool = is_hit(ground_truth, pool_10)

    reranked_result = retrieve_scoped_reranked(title, question, category, index_hybrid, rerank_top_n=3)

    print("=" * 100)
    print(f"Categorie: {category}")
    print(f"Question: {question}")
    print(f"Ground truth: {ground_truth}")
    print(f"Bon chunk present dans le pool top-10 avant reranking ? {'OUI' if gt_in_pool else 'NON'}")
    print("-" * 100)
    print("Top 3 APRES reranking (avec scores) :")
    for r in reranked_result:
        print(f"  score={r['score']}: {r['text'][:150]}...")

====================================================================================================
Categorie: Agreement Date
Question: Highlight the parts (if any) of this contract related to "Agreement Date" that should be reviewed by a lawyer. Details: The date of the contract
Ground truth: ['June 23, 2015']
Bon chunk present dans le pool top-10 avant reranking ? OUI
----------------------------------------------------------------------------------------------------
Top 3 APRES reranking (avec scores) :
  score=0.013447846285998821: Page of 7 of Sponsorship Agreement

17. Governing Law and Venue. This Agreement is to be governed and construed according to the laws of the State of ...
  score=0.002166120568290353: Page of 6 of Sponsorship Agreement

13. Notices. All notices and payment given in accordance with this Agreement will be effective if hand delivered o...
  score=0.0008895997307263315: The Sponsor must provide the consideration in Section 2 regardless of whether the Event is actually held. 9. Warranties. (a) The Sponsor's Warranty. T...
====================================================================================================
Categorie: Agreement Date
Question: Highlight the parts (if any) of this contract related to "Agreement Date" that should be reviewed by a lawyer. Details: The date of the contract
Ground truth: ['July 16, 2012']
Bon chunk present dans le pool top-10 avant reranking ? OUI
----------------------------------------------------------------------------------------------------
Top 3 APRES reranking (avec scores) :
  score=0.0028657671064138412: Pre-Acceptance Period. If and to the extent any such decision would or could (or would or could be reasonably foreseeable to) adversely affect any Spo...
  score=0.0017178015550598502: SPONSORSHIP AGREEMENT THIS SPONSORSHIP AGREEMENT ("Agreement") is entered into and effective as of the date first written above ("Effective Date") by ...
  score=0.0014868751168251038: 16. No Recourse. Notwithstanding anything that may be expressed or implied in this Agreement or any document or instrument delivered in connection her...
====================================================================================================
Categorie: Expiration Date
Question: Highlight the parts (if any) of this contract related to "Expiration Date" that should be reviewed by a lawyer. Details: On what date will the contract's initial term expire?
Ground truth: ['This Agreement shall commence on the Effective Date and shall extend for a period of Five (5) years thereafter ("Initial Term"), unless this Agreement is terminated earlier as provided herein or is extended by mutual written agreement of the Parties.']
Bon chunk present dans le pool top-10 avant reranking ? OUI
----------------------------------------------------------------------------------------------------
Top 3 APRES reranking (avec scores) :
  score=0.00038729311199858785: 11.3 Limitation of Liability. NEITHER PARTY SHALL BE LIABLE, WHETHER BASED ON CONTRACT LAW, TORTS OR ANY OTHER AREA OF LAW, FOR ANY INDIRECT, INCIDENT...
  score=0.00037813145900145173: 6.3 Latent Defects; Contamination.

(a) As soon as either Party becomes aware of a Latent Defect in any lot of Product, but in no case later than (i) ...
  score=0.00036641539190895855: If this Agreement is terminated by Magenta pursuant to Section 7.2(a) or by Bachem pursuant to Section 7.2(b) or (c), Magenta shall also pay to Bachem...
====================================================================================================
Categorie: Expiration Date
Question: Highlight the parts (if any) of this contract related to "Expiration Date" that should be reviewed by a lawyer. Details: On what date will the contract's initial term expire?
Ground truth: ['This promotion shall begin on June 1,1999 and shall terminate June 1, 2000 (herein "Term")']
Bon chunk present dans le pool top-10 avant reranking ? OUI
----------------------------------------------------------------------------------------------------
Top 3 APRES reranking (avec scores) :
  score=0.005286369007080793: Judgment upon the award rendered by the arbitrator may be entered in any court having jurisdiction.

d. Each party shall bear its own cost of these pr...
  score=0.0018797785742208362: Each party shall indemnify the other party with respect to any loss or damage arising from the unauthorized disclosure or use of the Information by th...
  score=0.0005659155431203544: The parties intend that these negotiations be conducted by non-lawyer, business representatives. The discussions shall be left to the discretion of th...
====================================================================================================
Categorie: Expiration Date
Question: Highlight the parts (if any) of this contract related to "Expiration Date" that should be reviewed by a lawyer. Details: On what date will the contract's initial term expire?
Ground truth: ['This term of this Agreement commences on the Effective Date and terminates on August 2nd, 2015 upon completion of event.']
Bon chunk present dans le pool top-10 avant reranking ? OUI
----------------------------------------------------------------------------------------------------
Top 3 APRES reranking (avec scores) :
  score=0.00027852869243361056: Page of 7 of Sponsorship Agreement

17. Governing Law and Venue. This Agreement is to be governed and construed according to the laws of the State of ...
  score=0.00024774280609562993: The Sponsor will not, at any time after the Effective Date, dispute or contest, directly or indirectly, ANTHEMIC's exclusive ownership in their respec...
  score=0.00020342232892289758: Construction. All parties have been advised to seek their own independent counsel concerning the interpretation and legal effect of this Agreement and...

In [33]:
from llama_index.core.postprocessor import SentenceTransformerRerank
reranker = SentenceTransformerRerank(
    model="BAAI/bge-reranker-v2-m3",
    top_n=3
)

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 5051.01it/s]

In [71]:
import pickle

checkpoint = {
    "baseline_hit_rate": baseline_hit_rate,
    "baseline_hit_vy_category": baseline_hit_vy_category,
    "baseline_df": baseline_df,
    "bge_large_hit_rate": bge_large_hit_rate,
    "bge_large_hit_vy_category": bge_large_hit_vy_category,
    "bge_large_df": bge_large_df,
    "nomic_hit_rate": nomic_hit_rate,
    "nomic_hit_vy_category": nomic_hit_vy_category,
    "nomic_df": nomic_df,
    "e5_hit_rate": e5_hit_rate,
    "e5_hit_by_category": e5_hit_by_category,
    "e5_df": e5_df,
    "hybrid_hit_rate": hybrid_hit_rate,
    "hybrid_hit_by_category": hybrid_hit_by_category,
    "hybrid_df": hybrid_df,
    "reranked_hit_rate": reranked_hit_rate,
    "reranked_hit_by_category": reranked_hit_by_category,
    "reranked_df": reranked_df,
    "merged": merged,
    "positive_sample": positive_sample,
    "negative_sample": negative_sample,
    "category_to_tier": category_to_tier,
}

with open("../artifacts/baseline_v2_checkpoint.pkl", "wb") as f:
    pickle.dump(checkpoint, f)

print("Checkpoint sauvegarde.")

Checkpoint sauvegarde.

In [1]:
import pickle

with open("../artifacts/baseline_v2_checkpoint.pkl", "rb") as f:
    checkpoint = pickle.load(f)

baseline_hit_rate = checkpoint["baseline_hit_rate"]
baseline_hit_vy_category = checkpoint["baseline_hit_vy_category"]
baseline_df = checkpoint["baseline_df"]
bge_large_hit_rate = checkpoint["bge_large_hit_rate"]
bge_large_hit_vy_category = checkpoint["bge_large_hit_vy_category"]
bge_large_df = checkpoint["bge_large_df"]
nomic_hit_rate = checkpoint["nomic_hit_rate"]
nomic_hit_vy_category = checkpoint["nomic_hit_vy_category"]
nomic_df = checkpoint["nomic_df"]
e5_hit_rate = checkpoint["e5_hit_rate"]
e5_hit_by_category = checkpoint["e5_hit_by_category"]
e5_df = checkpoint["e5_df"]
hybrid_hit_rate = checkpoint["hybrid_hit_rate"]
hybrid_hit_by_category = checkpoint["hybrid_hit_by_category"]
hybrid_df = checkpoint["hybrid_df"]
reranked_hit_rate = checkpoint["reranked_hit_rate"]
reranked_hit_by_category = checkpoint["reranked_hit_by_category"]
reranked_df = checkpoint["reranked_df"]
merged = checkpoint["merged"]
positive_sample = checkpoint["positive_sample"]
negative_sample = checkpoint["negative_sample"]
category_to_tier = checkpoint["category_to_tier"]

print("Checkpoint recharge.")

Checkpoint recharge.

In [21]:
from llama_index.embeddings.ollama import OllamaEmbedding
nomic_embed = OllamaEmbedding(model_name="nomic-embed-text")

In [23]:
from llama_index.vector_stores.qdrant import QdrantVectorStore
from llama_index.core import VectorStoreIndex, StorageContext
vector_store_hybrid = QdrantVectorStore(
    collection_name="cuad_nomic_bm25_hybrid",
    client=client,
    enable_hybrid=True,
    fastembed_sparse_model="Qdrant/bm25",
)
index_hybrid = VectorStoreIndex.from_vector_store(vector_store_hybrid, embed_model=nomic_embed)

In [30]:
from llama_index.core.vector_stores import MetadataFilters, ExactMatchFilter

In [34]:
reranked_m3_hit_rate, reranked_m3_hit_by_category, reranked_m3_df = compute_hit_rate_reranked(
    positive_sample, index_hybrid
)
print(f"Hybrid + reranking hit rate: {reranked_m3_hit_rate:.3f}")

Hybrid + reranking hit rate: 0.644

In [36]:
reranked_m3_hit_by_category

category
Minimum Commitment                    0.0
Most Favored Nation                   0.0
Revenue/Profit Sharing                0.0
Rofr/Rofo/Rofn                        0.2
Competitive Restriction Exception     0.2
Volume Restriction                    0.4
Expiration Date                       0.4
No-Solicit Of Customers               0.4
Non-Compete                           0.4
Covenant Not To Sue                   0.4
Ip Ownership Assignment               0.4
Liquidated Damages                    0.4
Post-Termination Services             0.6
Price Restrictions                    0.6
Termination For Convenience           0.6
Unlimited/All-You-Can-Eat-License     0.6
Non-Disparagement                     0.6
Warranty Duration                     0.6
Affiliate License-Licensor            0.6
Insurance                             0.6
Agreement Date                        0.6
Exclusivity                           0.6
Effective Date                        0.6
License Grant                         0.8
Source Code Escrow                    0.8
Audit Rights                          0.8
Joint Ip Ownership                    0.8
Affiliate License-Licensee            0.8
Non-Transferable License              0.8
Irrevocable Or Perpetual License      0.8
Parties                               1.0
Cap On Liability                      1.0
Renewal Term                          1.0
Document Name                         1.0
Anti-Assignment                       1.0
No-Solicit Of Employees               1.0
Governing Law                         1.0
Third Party Beneficiary               1.0
Uncapped Liability                    1.0
Notice Period To Terminate Renewal    1.0
Change Of Control                     1.0
Name: hit, dtype: float64

In [38]:
negative_sample[0]

{'title': 'VERTICALNETINC_04_01_2002-EX-10.19-MAINTENANCE AND SUPPORT AGREEMENT',
 'question': 'Highlight the parts (if any) of this contract related to "Notice Period To Terminate Renewal" that should be reviewed by a lawyer. Details: What is the notice period required to terminate renewal?',
 'category': 'Notice Period To Terminate Renewal'}

In [39]:
def compute_scores_for_sample(sample, index, retrieve_fn=retrieve_scoped_reranked, rerank_top_n=3):
    results = []
    for item in sample:
        title = item["title"]
        question = item["question"]
        category = item["category"]

        retrieved = retrieve_fn(title, question, category, index, rerank_top_n=rerank_top_n)
        scores = [r["score"] for r in retrieved if r["score"] is not None]
        top_score = max(scores) if scores else None

        results.append({
            "title": title,
            "category": category,
            "top_score": top_score,
        })

    return pd.DataFrame(results)

negative_scores_df = compute_scores_for_sample(negative_sample, index_hybrid)

In [40]:
positive_scores_df = reranked_m3_df[["title", "category"]].copy()
positive_scores_df["top_score"] = reranked_m3_df["retrieved_scores"].apply(
    lambda scores: max([s for s in scores if s is not None], default=None)
)

In [41]:
print("Positifs (clause presente) - distribution du meilleur score :")
print(positive_scores_df["top_score"].describe())

print("\nNegatifs (clause absente) - distribution du meilleur score :")
print(negative_scores_df["top_score"].describe())

Positifs (clause presente) - distribution du meilleur score :
count    195.000000
mean       0.160974
std        0.231528
min        0.002477
25%        0.015265
50%        0.046863
75%        0.194767
max        0.890346
Name: top_score, dtype: float64

Negatifs (clause absente) - distribution du meilleur score :
count    117.000000
mean       0.036352
std        0.067611
min        0.000220
25%        0.007452
50%        0.014016
75%        0.037409
max        0.517739
Name: top_score, dtype: float64

In [42]:
import re

def strip_boilerplate(question):
    match = re.search(r'"([^"]+)"', question)
    category_quoted = match.group(0) if match else ""
    details = question.split("Details: ", 1)[1] if "Details: " in question else ""
    return f"{category_quoted}. {details}".strip()

def retrieve_scoped_reranked_short_q(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.get_content(), "score": None} for n in selected]

    filtered_retriever = index.as_retriever(
        similarity_top_k = retrieve_top_k,
        sparse_too_k = sparse_top_k,
        vector_store_query_mode = "hybrid",
        filters = MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)]) 
    )
    retrieved_nodes = filtered_retriever.retrieve(question)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    return [{"text":n.get_content(), "score":n.score} for n in reranked_nodes]

In [44]:
from llama_index.core.postprocessor import SentenceTransformerRerank

reranker = SentenceTransformerRerank(model="BAAI/bge-reranker-large", top_n=3)

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 6264.75it/s]

In [45]:

reranked_large_short_hit_rate, reranked_large_short_hit_by_category, reranked_large_short_df = compute_hit_rate_reranked(
    positive_sample, index_hybrid, retrieve_fn=retrieve_scoped_reranked_short_q
)
print(f"Hybrid + bge-reranker-large (514 tok) + question raccourcie: {reranked_large_short_hit_rate:.3f}")

Hybrid + bge-reranker-large (514 tok) + question raccourcie: 0.688

In [46]:
reranked_large_short_hit_by_category

category
Minimum Commitment                    0.0
Revenue/Profit Sharing                0.0
Most Favored Nation                   0.2
Liquidated Damages                    0.4
Rofr/Rofo/Rofn                        0.4
Competitive Restriction Exception     0.4
Covenant Not To Sue                   0.4
Exclusivity                           0.4
Ip Ownership Assignment               0.4
Termination For Convenience           0.6
No-Solicit Of Customers               0.6
Non-Compete                           0.6
Non-Disparagement                     0.6
Non-Transferable License              0.6
Post-Termination Services             0.6
Unlimited/All-You-Can-Eat-License     0.6
Volume Restriction                    0.6
Price Restrictions                    0.6
Affiliate License-Licensor            0.6
Effective Date                        0.6
Source Code Escrow                    0.8
Notice Period To Terminate Renewal    0.8
Affiliate License-Licensee            0.8
Warranty Duration                     0.8
Joint Ip Ownership                    0.8
Irrevocable Or Perpetual License      0.8
Insurance                             0.8
Agreement Date                        0.8
Expiration Date                       0.8
Cap On Liability                      0.8
Uncapped Liability                    1.0
Third Party Beneficiary               1.0
Anti-Assignment                       1.0
Audit Rights                          1.0
No-Solicit Of Employees               1.0
License Grant                         1.0
Document Name                         1.0
Parties                               1.0
Governing Law                         1.0
Change Of Control                     1.0
Renewal Term                          1.0
Name: hit, dtype: float64

In [47]:
negative_large_short_scores_df = compute_scores_for_sample(negative_sample, index_hybrid)

In [49]:
positive_large_short_scores_df = reranked_large_short_df[["title", "category"]].copy()
positive_large_short_scores_df["top_score"] = reranked_large_short_df["retrieved_scores"].apply(
    lambda scores: max([s for s in scores if s is not None], default=None)
)

In [50]:
print("Positifs (clause presente) - distribution du meilleur score :")
print(positive_large_short_scores_df["top_score"].describe())

print("\nNegatifs (clause absente) - distribution du meilleur score :")
print(negative_large_short_scores_df["top_score"].describe())

Positifs (clause presente) - distribution du meilleur score :
count    195.000000
mean       0.053256
std        0.125090
min        0.000100
25%        0.000731
50%        0.003633
75%        0.033293
max        0.786843
Name: top_score, dtype: float64

Negatifs (clause absente) - distribution du meilleur score :
count    117.000000
mean       0.003114
std        0.007262
min        0.000098
25%        0.000548
50%        0.000978
75%        0.002355
max        0.054334
Name: top_score, dtype: float64

In [51]:
current_failures = reranked_large_short_df[reranked_large_short_df["hit"] == 0]
print(f"Echecs avec le pipeline actuel : {len(current_failures)} / {len(reranked_large_short_df)}")
print(current_failures["category"].value_counts())

Echecs avec le pipeline actuel : 64 / 205
category
Minimum Commitment                    5
Revenue/Profit Sharing                5
Most Favored Nation                   4
Exclusivity                           3
Rofr/Rofo/Rofn                        3
Liquidated Damages                    3
Covenant Not To Sue                   3
Ip Ownership Assignment               3
Competitive Restriction Exception     3
Volume Restriction                    2
Effective Date                        2
Affiliate License-Licensor            2
Unlimited/All-You-Can-Eat-License     2
Non-Transferable License              2
Termination For Convenience           2
Non-Disparagement                     2
Non-Compete                           2
Post-Termination Services             2
Price Restrictions                    2
No-Solicit Of Customers               2
Cap On Liability                      1
Irrevocable Or Perpetual License      1
Notice Period To Terminate Renewal    1
Insurance                             1
Warranty Duration                     1
Affiliate License-Licensee            1
Joint Ip Ownership                    1
Source Code Escrow                    1
Expiration Date                       1
Agreement Date                        1
Name: count, dtype: int64

In [53]:
import random

failure_pool = merged[(merged["n_hits"] == 0) & (~merged["category"].isin(["Document Name", "Parties"]))]

random.seed(123)
sample_indices = random.sample(list(failure_pool.index), 10)
inspection_sample = failure_pool.loc[sample_indices]

positive_lookup = {(item["title"], item["question"]): item for item in positive_sample}

In [54]:
sample_fail = current_failures.sample(min(10, len(current_failures)), random_state=456)

for _, row in sample_fail.iterrows():
    item = positive_lookup[(row["title"], row["question"])]
    ground_truth = item["ground_truth"]

    print("=" * 100)
    print(f"Categorie: {row['category']}")
    print(f"Ground truth: {ground_truth}")
    print(f"Scores des chunks retenus: {row['retrieved_scores']}")
    print("-" * 100)
    for i, chunk in enumerate(row["retrieved_chunks"]):
        print(f"[Chunk {i}]\n{chunk[:300]}...\n")

====================================================================================================
Categorie: Agreement Date
Ground truth: ['October 15, 2009']
Scores des chunks retenus: [np.float32(0.051060334), np.float32(0.049580794), np.float32(0.048407525)]
----------------------------------------------------------------------------------------------------
[Chunk 0]
Effective as of the Agreement Date, PPI hereby sells, transfers, conveys and assigns to EKR all right, title and interest in and to [**] (the "Transferred NDA"). Each Party shall, within five (5) business days after the Agreement Date, file with the FDA a notice letter, substantially in the form att...

[Chunk 1]
On the Agreement Date, PPI shall execute and deliver to EKR a Bill of Sale with respect to the Transferred Equipment substantially in the form attached hereto as Exhibit 3.20(a). (b) EKR will pay PPI [**] Dollars ($[**]) for the Transferred Equipment (the "Equipment Purchase Price") as follows:

(i)...

[Chunk 2]
3.4 Assistance. PPI shall, at EKR's cost and expense, provide EKR with all assistance, information and guidance, including where appropriate direct access to employees of and consultants to PPI and its Affiliates and shall use reasonable efforts to obtain such assistance and access from any sub-cont...

====================================================================================================
Categorie: Competitive Restriction Exception
Ground truth: ['We shall have no obligation to enforce similar covenants against any other System franchisee.', 'As a result, you agree that the following locations ("Special Sites") are excluded from the Designated Area and we shall have the right to develop (by direct ownership or franchising) such locations: 1) public transportation facilities, including airports, train stations and bus stations; 2) military bases; 3) sports facilities, including race tracks; and 4) amusement and/or theme parks.', 'Although we will not operate a Buffalo Wild Wings or bw-3 business within the Designated Area, we reserve the right, both within and outside of the Designated Area, to offer and sell at special events (at our option, if you elect not to participate in such events) or at wholesale, through channels of distribution distinct from those of a Franchised Restaurant, products and services which comprise, or may in the future comprise a part of the System, which products may be resold at retail to the general public by such entities.', 'We reserve the right to market and sell Menu Items and Trade Secret Food Products on the Internet/World Wide Web.']
Scores des chunks retenus: [np.float32(0.0009021143), np.float32(0.0006120073), np.float32(0.00043714978)]
----------------------------------------------------------------------------------------------------
[Chunk 0]
2. CONFIDENTIALITY AND NON-COMPETITION AGREEMENTS.

A. IN TERM COVENANT NOT-TO-COMPETE. Each of you agrees that during the period Franchisee operates any Buffalo Wild Wings and/or bw-3 Restaurants, or has any beneficial interest therein, or holds any rights to develop one or more such Restaurants (i...

[Chunk 1]
("we" or "us") of an Area Development Agreement and/or one or more Franchise Agreements executed (collectively the "Agreements") providing certain rights relating to Buffalo Wild Wings Restaurants (the "Restaurants") to ________________________ ________________ ("Franchisee"), each of the undersigne...

[Chunk 2]
D. INFRINGEMENT; VALIDITY OF MARKS AND COPYRIGHTS; REGISTRATIONS. You will not at any time commit any act that would infringe upon or impair the value of the System or the Marks, nor will you engage in any business or market any product or service under a name, mark, or design that is confusingly or...

====================================================================================================
Categorie: Volume Restriction
Ground truth: ["Customer's data traffic between the e-business Hosting Center and the Internet may not exceed Committed Bandwidth, unless otherwise expressly specified in an Attachment.", "If Customer's Peak Bandwidth Usage for the month exceeds Committed Bandwidth, Customer will incur a Peak Bandwidth Usage charge, for the amount of usage that exceeds Committed Bandwidth, at the rate specified in Attachment C.", 'Customer is allowed up to three (3) emergency requests per month at no additional charge.', 'Restore System Images at no additional charge up to two (2) times per month per Managed Server per Customer.']
Scores des chunks retenus: [np.float32(0.0027920045), np.float32(0.0010301803), np.float32(0.0004560952)]
----------------------------------------------------------------------------------------------------
[Chunk 0]
IBM reserves the right to adjust the thresholds for any monitored event in order to reduce the instances of false positives. Customer will be notified in of the change.

Page 18 of 36

Source: QUANTUM GROUP INC /FL, 8-K, 1/20/2009

IBM will: Monitor all network interface cards (NIC); Monitor the fol...

[Chunk 1]
Waiver of Jury Trial The parties waive any right to a jury trial in any proceeding arising out of or related to this Agreement. Severability If any provision of this Agreement shall be held by a court of competent jurisdiction to be invalid, illegal, or unenforceable, the validity, legality, and enf...

[Chunk 2]
IBM will adhere to reasonable terms and conditions pertaining to Customer Components as notified in writing to IBM. IBM agrees not to remove or alter any copyright or other proprietary notice on or in any Customer Component without Customer's consent. Capacity Planning Customer acknowledges it is it...

====================================================================================================
Categorie: Termination For Convenience
Ground truth: ['This Agreement may be terminated by WYZZ by written notice to Nexstar (i) at any time upon six (6) months prior written notice, (ii) on six (6) months prior notice following the sale of WMBD-TV by Nexstar and/or (iii) if WYZZ is not then in material default or breach hereof and if the Nexstar is in material breach of its representations or its material obligations hereunder, and has failed to cure such breach within thirty (30) days of notice from WYZZ; provided, no notice may be given pursuant to clause (i) of this section prior to the eighteen (18) month anniversary of the Effective Date.', 'This Agreement may be terminated by Nexstar by written notice to WYZZ (i) any time upon six (6) months prior notice, (ii) on six (6) months prior notice following the sale of WYZZ-TV by WYZZ, and/or (iii) if Nexstar is not then in material default or breach hereof, and WYZZ is in material breach of its representations or its material obligations hereunder, and has failed to cure such breach within thirty (30) days of written notice from Nexstar; provided, no notice may be given pursuant to clause (i) of this section prior to the eighteen (18) month anniversary of the Effective Date.']
Scores des chunks retenus: [np.float32(0.0023557039), np.float32(0.0014484788), np.float32(0.0011123297)]
----------------------------------------------------------------------------------------------------
[Chunk 0]
15L. Contracts. Schedule 15L to this Exhibit lists all written Contracts and true and complete descriptions of all material oral contracts (including any amendments or other modifications to such Contracts). All of the Contracts are

in full force and effect, and are valid, binding, and enforceable ...

[Chunk 1]
c. Termination due to invalidity or material change. Unless terminated pursuant to another provisions of this Agreement, this Agreement will terminate upon the first to occur of any of the following:

(i) this Agreement is declared invalid or illegal in whole or substantial part by an order or decre...

[Chunk 2]
15P. Contracts. Schedule 15P to this Exhibit lists all written Contracts and true and complete descriptions of all oral contracts (including any

amendments or other modifications to such Contracts). All of the Contracts are in full force and effect, and are valid, binding, and enforceable in accord...

====================================================================================================
Categorie: Non-Disparagement
Ground truth: ["Company and North shall at all times deal with each other in good faith and strive to maintain and enhance each other's positive  image and reputation."]
Scores des chunks retenus: [np.float32(0.0004985984), np.float32(0.00048078943), np.float32(0.0002802147)]
----------------------------------------------------------------------------------------------------
[Chunk 0]
The parties hereto agree not to disclose any such terms, amounts or information to any other person or entity whatsoever other than its attorneys, accountants, or as required by law.

31. Counterparts. This Agreement may be executed in one or more counterparts, each of which shall be deemed an origi...

[Chunk 1]
Assignment. Neither party to this Agreement shall assign the rights and benefits herein without the prior written consent of the other party.

20. Independent Contractor. Company has engaged North for certain rights which are set forth in this Agreement, and North's relationship to Company, and Comp...

[Chunk 2]
26. Severability. The illegality, unenforceability or invalidity of any term, clause or provision of this Agreement shall not affect any other term, clause or provision hereof, and this Agreement shall continue in full force and effect, and be construed and enforced, as if such provision had not bee...

====================================================================================================
Categorie: No-Solicit Of Customers
Ground truth: ['Unless otherwise instructed by Sonos in writing, IAC is not authorized at any time to sell Custom Components to any third party or IAC Affiliate.']
Scores des chunks retenus: [np.float32(0.00048289023), np.float32(0.00030182625), np.float32(0.00017128598)]
----------------------------------------------------------------------------------------------------
[Chunk 0]
13.2. No Product will be (i) produced, manufactured, assembled, tested, or packaged by forced, prison, or child (defined as age 14 or below or the minimum working age within the applicable jurisdiction, whichever is older) labor, or (ii) transshipped for the purpose of mislabeling, evading quota or ...

[Chunk 1]
For clarification purposes, an industry wide inability to obtain a Third Party Component is a force majeure event; however, all other material shortages shall not be considered force majeure events. The party claiming excuse because of force majeure shall use its commercially reasonable efforts to p...

[Chunk 2]
Titles and headings to articles and sections of this Agreement are inserted for convenience of reference only and are not intended to affect the interpretation or construction of this Agreement. The terms "this Agreement," "herein," "hereof," "hereunder" and similar expressions refer to this Agreeme...

====================================================================================================
Categorie: Minimum Commitment
Ground truth: ['Notwithstanding Sections 6.4, 6.5, and 6.6, the Royalty Payment to Array shall not be reduced in any calendar quarter (a) during the Initial Royalty Term to less than [ * ] of the amount due under Section 6.3(a)(i), and (b) during the Secondary Royalty Term to less than [ * ] of the amount due under Section 6.3(a) (ii) (provided that any amounts in excess of the permitted deduction shall be carried forward to the subsequent calendar quarters until exhausted), unless 6.4(b) applies in which case royalty shall be as set forth therein.']
Scores des chunks retenus: [np.float32(0.00042324176), np.float32(0.00041264406), np.float32(0.00018919788)]
----------------------------------------------------------------------------------------------------
[Chunk 0]
The request shall indicate the grounds on which it is based. The Parties shall then consult one another with a view to revising the contract an equitable basis, in order to ensure that neither Party suffers excessive prejudice. The request for revision does not of itself suspend performance of the c...

[Chunk 1]
10.5 Abstracts, Posters and Slide Decks. If a Party (or a Clinical Study site contracted by such Party as sponsor of the relevant Clinical Study) intends to present findings with respect to a Product at symposia or other meetings of healthcare professionals, or international and/or US, European or J...

[Chunk 2]
For clarity, the forgoing supply obligations not apply to materials that are generally commercially available.

9.3 Clinical Supply. The Parties shall establish as soon as practicable following the Effective Date procedures for the supply of Materials to Ono for use in performing Ono's Development a...

====================================================================================================
Categorie: Cap On Liability
Ground truth: ['IN NO EVENT SHALL EITHER PARTY BE LIABLE TO THE OTHER FOR ANY SPECIAL, INDIRECT, EXEMPLARY OR CONSEQUENTIAL DAMAGES ARISING OUT OF THIS AGREEMENT OR PURCHASE OR USE OF THE PRODUCTS.']
Scores des chunks retenus: [np.float32(0.055018216), np.float32(0.015172674), np.float32(0.008151702)]
----------------------------------------------------------------------------------------------------
[Chunk 0]
8. RIGHTS OF PARTIES AT TERMINATION. (a) Obligations After Termination. In the event that this Agreement is terminated or expires on its own terms, Company shall have no further responsibilities to Distributor except that in the event the Agreement terminates for any reason other than a breach hereo...

[Chunk 1]
(g) The obligations of the Recipient Party under this Section 6 shall survive termination or nonrenewal of this Agreement for a period of thee (3) years. For the avoidance of doubt, the customer and sub-distributor lists of Distributor shall be deemed to constitute Proprietary Information under this...

[Chunk 2]
The Recipient Party may disclose the Proprietary Information to the extent required by a valid order by a court or other governmental body or by applicable law; provided, however, that the Recipient Party will use all reasonable efforts to notify Disclosing Party of the obligation to make such discl...

====================================================================================================
Categorie: Most Favored Nation
Ground truth: ['All Users shall be treated at least as favorable in all respects (including without limitation with respect to pricing, quality of service, and customer support responsiveness) as Boxlot treats users of the Boxlot Site.']
Scores des chunks retenus: [np.float32(0.0013049074), np.float32(0.0010404905), np.float32(0.0008286685)]
----------------------------------------------------------------------------------------------------
[Chunk 0]
In addition, Boxlot shall indemnify theglobe against any and all claims, losses, costs and expenses, including reasonable attorneys' fees, which theglobe may incur as a result of claims in any form by third parties arising from Boxlot Banners, Boxlot Content, Boxlot Marks, the Service (excluding the...

[Chunk 1]
12.6 Severability; Headings. If any provision herein is held to be invalid or unenforceable for any reason, the remaining provisions will continue in full force without being impaired or invalidated in any way. The parties agree to replace any invalid provision with a valid provision that most close...

[Chunk 2]
Thus, in the event that this Agreement terminates under Section 8.2 [Termination for Failure to Perform] due to Boxlot's failure to perform (excluding the cross-reference to Section 12.7 [Force Majeure]) prior to the end of the applicable year, Boxlot shall immediately pay to theglobe the amount nec...

====================================================================================================
Categorie: Non-Transferable License
Ground truth: ['Notwithstanding the forgoing, subject to Section 4.02(b) and ARTICLE VI, members of the Nuance Group may only sublicense the SpinCo Shared Technology Assets pursuant to terms and conditions as protective as those under which it licenses its own Technology of a similar nature and value, and in any event terms and conditions that provide for commercially reasonable protection for the source code, structure and other confidential and proprietary elements of the SpinCo Shared Technology Assets.', 'The licenses granted in Sections 4.01(a), (b) and (c) to the Nuance Group include the right to grant sublicenses within the scope of such licenses only to members of the Nuance Group and, without any further right to sublicense, to their respective (i) contractors, distributors, manufacturers and resellers, in each case solely for the benefit of the Nuance Business and (ii) end users and customers, in each case solely in connection with the use of products and services of the Nuance Business.']
Scores des chunks retenus: [np.float32(0.1839575), np.float32(0.021189163), np.float32(0.019735951)]
----------------------------------------------------------------------------------------------------
[Chunk 0]
Section 8.02. Divested Businesses. In the event a Party divests a line of business or line of products or services by (a) spinning off a member of its Group by its sale or other disposition to a Third Party, (b) reducing ownership or control in a member of its Group so that it no longer qualifiers a...

[Chunk 1]
Any purported assignment without such consent shall be void. Notwithstanding the foregoing, if any Party to this Agreement (or any of its successors or permitted assigns) (a) shall enter into a consolidation or merger transaction in which such Party is not the surviving entity and the surviving enti...

[Chunk 2]
(b) With respect to the SpinCo Shared Technology Assets, Nuance agrees that it will not (i) engage in any act, or purposefully omit to perform any act, that impairs or adversely affects the rights of SpinCo or any member of the SpinCo Group in and to any SpinCo Shared Technology Assets, (ii) use the...

In [55]:
checkpoint["reranked_large_short_hit_rate"] = reranked_large_short_hit_rate
checkpoint["reranked_large_short_hit_by_category"] = reranked_large_short_hit_by_category
checkpoint["reranked_large_short_df"] = reranked_large_short_df
checkpoint["positive_large_short_scores_df"] = positive_large_short_scores_df
checkpoint["negative_large_short_scores_df"] = negative_large_short_scores_df

with open("../artifacts/baseline_v2_checkpoint.pkl", "wb") as f:
    pickle.dump(checkpoint, f)

print("Baseline v2 figee et sauvegardee (0.688).")

Baseline v2 figee et sauvegardee (0.688).

In [56]:
category_to_tier

{'Agreement Date': 2,
 'Document Name': 1,
 'Effective Date': 2,
 'Parties': 1,
 'Governing Law': 2,
 'Expiration Date': 2,
 'Third Party Beneficiary': 2,
 'Termination For Convenience': 2,
 'Notice Period To Terminate Renewal': 2,
 'Renewal Term': 2,
 'Anti-Assignment': 2,
 'No-Solicit Of Customers': 2,
 'Volume Restriction': 2,
 'No-Solicit Of Employees': 2,
 'Most Favored Nation': 2,
 'Price Restrictions': 2,
 'Uncapped Liability': 2,
 'Covenant Not To Sue': 2,
 'Non-Disparagement': 2,
 'Unlimited/All-You-Can-Eat-License': 2,
 'Liquidated Damages': 2,
 'Warranty Duration': 2,
 'Competitive Restriction Exception': 2,
 'Change Of Control': 2,
 'Exclusivity': 2,
 'Joint Ip Ownership': 2,
 'Non-Compete': 2,
 'Revenue/Profit Sharing': 2,
 'Minimum Commitment': 3,
 'Non-Transferable License': 3,
 'Cap On Liability': 3,
 'Audit Rights': 3,
 'Ip Ownership Assignment': 3,
 'Insurance': 3,
 'Affiliate License-Licensee': 3,
 'Post-Termination Services': 3,
 'License Grant': 3,
 'Irrevocable Or Perpetual License': 3,
 'Rofr/Rofo/Rofn': 3,
 'Affiliate License-Licensor': 3,
 'Source Code Escrow': 3}

In [71]:
DISPERSED_RESPONSES = {"Minimum Commitment",
"Revenue/Profit Sharing",
"Most Favored Nation",
"Exclusivity",
"Rofr/Rofo/Rofn",
"Liquidated Damages",
"Covenant Not To Sue",
"Ip Ownership Assignment",
"Competitive Restriction Exception",
"Volume Restriction",
"Effective Date",
"Affiliate License-Licensor",
"Unlimited/All-You-Can-Eat-License",
"Non-Transferable License",
"Termination For Convenience",
"Non-Disparagement",
"Non-Compete",
"Post-Termination Services",
"Price Restrictions",
"No-Solicit Of Customers"}

In [72]:
def retrieve_scoped_reranked_adaptive_topk(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in nodes if n.metadata["title"]==title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.get_content(), "score": None} for n in selected]

    if category in DISPERSED_RESPONSES:
        retrieve_top_k=15
        sparse_top_k=15
        rerank_top_n=5
    
    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    return [{"text": n.get_content(), "score": n.score} for n in reranked_nodes]

In [73]:
adaptive_hit_rate, adaptive_hit_by_category, adaptive_df = compute_hit_rate_reranked(
    positive_sample, index_hybrid, retrieve_fn=retrieve_scoped_reranked_adaptive_topk
)
print(f"top_k adaptif (large loop for disperded responses): {adaptive_hit_rate:.3f}")

top_k adaptif (large loop for disperded responses): 0.746

In [74]:
adaptive_hit_by_category

category
Minimum Commitment                    0.0
Most Favored Nation                   0.2
Revenue/Profit Sharing                0.2
Exclusivity                           0.4
Competitive Restriction Exception     0.4
Covenant Not To Sue                   0.4
Liquidated Damages                    0.4
Rofr/Rofo/Rofn                        0.6
Ip Ownership Assignment               0.6
Non-Disparagement                     0.6
No-Solicit Of Customers               0.6
Unlimited/All-You-Can-Eat-License     0.6
Volume Restriction                    0.6
Post-Termination Services             0.6
Notice Period To Terminate Renewal    0.8
Non-Transferable License              0.8
Source Code Escrow                    0.8
Affiliate License-Licensee            0.8
Cap On Liability                      0.8
Affiliate License-Licensor            0.8
Agreement Date                        0.8
Joint Ip Ownership                    0.8
Effective Date                        0.8
Warranty Duration                     0.8
Expiration Date                       0.8
Irrevocable Or Perpetual License      0.8
Insurance                             0.8
Non-Compete                           1.0
Uncapped Liability                    1.0
Third Party Beneficiary               1.0
Termination For Convenience           1.0
Anti-Assignment                       1.0
Audit Rights                          1.0
Renewal Term                          1.0
Price Restrictions                    1.0
Governing Law                         1.0
Parties                               1.0
Change Of Control                     1.0
Document Name                         1.0
No-Solicit Of Employees               1.0
License Grant                         1.0
Name: hit, dtype: float64

In [75]:
current_failures = adaptive_df[adaptive_df["hit"] == 0]
print(f"Echecs avec le pipeline actuel : {len(current_failures)} / {len(adaptive_df)}")
print(current_failures["category"].value_counts())

Echecs avec le pipeline actuel : 52 / 205
category
Minimum Commitment                    5
Most Favored Nation                   4
Revenue/Profit Sharing                4
Covenant Not To Sue                   3
Exclusivity                           3
Liquidated Damages                    3
Competitive Restriction Exception     3
Volume Restriction                    2
Unlimited/All-You-Can-Eat-License     2
Ip Ownership Assignment               2
Non-Disparagement                     2
Post-Termination Services             2
Rofr/Rofo/Rofn                        2
No-Solicit Of Customers               2
Cap On Liability                      1
Insurance                             1
Effective Date                        1
Warranty Duration                     1
Irrevocable Or Perpetual License      1
Notice Period To Terminate Renewal    1
Non-Transferable License              1
Affiliate License-Licensee            1
Joint Ip Ownership                    1
Expiration Date                       1
Source Code Escrow                    1
Affiliate License-Licensor            1
Agreement Date                        1
Name: count, dtype: int64

In [76]:
# 1. Reset : tous les Tier 3 actuels -> Tier 2
for category, tier in list(category_to_tier.items()):
    if tier == 3:
        category_to_tier[category] = 2

# 2. Promotion vers Tier 3 uniquement pour les categories qui ont prouve un gain avec le pool elargi
IMPROVED_WITH_WIDER_POOL = {
    "Termination For Convenience",
    "Non-Compete",
    "Price Restrictions",
    "Revenue/Profit Sharing",
    "Rofr/Rofo/Rofn",
    "Ip Ownership Assignment",
    "Effective Date",
    "Affiliate License-Licensor",
    "Non-Transferable License",
}

for category in IMPROVED_WITH_WIDER_POOL:
    category_to_tier[category] = 3

print(category_to_tier)

{'Agreement Date': 2, 'Document Name': 1, 'Effective Date': 3, 'Parties': 1, 'Governing Law': 2, 'Expiration Date': 2, 'Third Party Beneficiary': 2, 'Termination For Convenience': 3, 'Notice Period To Terminate Renewal': 2, 'Renewal Term': 2, 'Anti-Assignment': 2, 'No-Solicit Of Customers': 2, 'Volume Restriction': 2, 'No-Solicit Of Employees': 2, 'Most Favored Nation': 2, 'Price Restrictions': 3, 'Uncapped Liability': 2, 'Covenant Not To Sue': 2, 'Non-Disparagement': 2, 'Unlimited/All-You-Can-Eat-License': 2, 'Liquidated Damages': 2, 'Warranty Duration': 2, 'Competitive Restriction Exception': 2, 'Change Of Control': 2, 'Exclusivity': 2, 'Joint Ip Ownership': 2, 'Non-Compete': 3, 'Revenue/Profit Sharing': 3, 'Minimum Commitment': 2, 'Non-Transferable License': 3, 'Cap On Liability': 2, 'Audit Rights': 2, 'Ip Ownership Assignment': 3, 'Insurance': 2, 'Affiliate License-Licensee': 2, 'Post-Termination Services': 2, 'License Grant': 2, 'Irrevocable Or Perpetual License': 2, 'Rofr/Rofo/Rofn': 3, 'Affiliate License-Licensor': 3, 'Source Code Escrow': 2}

In [80]:
def retrieve_scoped_reranked_adaptive_topk(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.get_content(), "score": None} for n in selected]

    if tier == 3:
        retrieve_top_k = 15
        sparse_top_k = 15
        rerank_top_n = 5

    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    return [{"text": n.get_content(), "score": n.score} for n in reranked_nodes]

In [90]:
from llama_index.core.node_parser import SentenceWindowNodeParser

relevant_titles = set(item["title"] for item in positive_sample)
print(f"nbre de contrats uniques concernés: {len(relevant_titles)}")

relevant_contracts = [c for c in unique_contracts if c["title"] in relevant_titles]

sentence_documents = [
    Document(text=c["clean_context"], metadata={"title": c["title"]})
    for c in relevant_contracts
]

sentence_window_parser = SentenceWindowNodeParser.from_defaults(
    window_size=3,
    window_metadata_key="window",
    original_text_metadata_key="original_text"
)

sentence_nodes = sentence_window_parser.get_nodes_from_documents(sentence_documents)

counters = defaultdict(int)
for n in sentence_nodes:
    title = n.metadata["title"]
    n.metadata["chunk_index"]=counters[title]
    counters[title]+=1

print(f"nombre de phrases indexés: {len(sentence_nodes)}")
print(f"moy de phrases par contrat: {len(sentence_nodes)/len(relevant_contracts):.1f}")

nbre de contrats uniques concernés: 161
nombre de phrases indexés: 50675
moy de phrases par contrat: 314.8

In [91]:
vector_store_sentence = QdrantVectorStore(
    collection_name="cuad_sentence_widow_hybrid",
    client=client,
    enable_hybrid=True,
    fastembed_sparse_model="Qdrant/bm25"
)
storage_context_sentence=StorageContext.from_defaults(vector_store=vector_store_sentence)
index_sentence=VectorStoreIndex(sentence_nodes, storage_context=storage_context_sentence, embed_model=nomic_embed)

Fetching 18 files: 100%|██████████| 18/18 [00:02<00:00,  8.94it/s]
/Users/aitbellalhamza/Desktop/RAG-for-contract-understanding-CUAD/.cuad-venv/lib/python3.11/site-packages/llama_index/vector_stores/qdrant/base.py:852: UserWarning: Payload indexes have no effect in the local Qdrant. Please use server Qdrant if you need payload indexes.
  self._client.create_payload_index(
/Users/aitbellalhamza/Desktop/RAG-for-contract-understanding-CUAD/.cuad-venv/lib/python3.11/site-packages/qdrant_client/qdrant_client.py:1927: UserWarning: Local mode is not recommended for collections with more than 20,000 points. Current collection contains 20480 points. Consider using Qdrant in Docker or Qdrant Cloud for better performance with large datasets.
  return self._client.upload_points(

In [92]:
from llama_index.core.postprocessor import MetadataReplacementPostProcessor

metadata_replacer = MetadataReplacementPostProcessor(target_metadata_key="window")

def retrieve_scoped_sentence_window(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in sentence_nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.metadata.get("window", n.get_content()), "score": None} for n in selected]

    if tier == 3:
        retrieve_top_k = 15
        sparse_top_k = 15
        rerank_top_n = 5

    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)
    retrieved_nodes = metadata_replacer.postprocess_nodes(retrieved_nodes)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    return [{"text": n.get_content(), "score": n.score} for n in reranked_nodes]

In [93]:
sentence_window_hit_rate, sentence_window_hit_by_category, sentence_window_df = compute_hit_rate_reranked(
    positive_sample, index_sentence, retrieve_fn=retrieve_scoped_sentence_window
)
print(f"Sentence-window chunking hit rate: {sentence_window_hit_rate:.3f}")

Sentence-window chunking hit rate: 0.678

In [94]:
sentence_window_hit_by_category

category
Most Favored Nation                   0.0
Exclusivity                           0.0
Minimum Commitment                    0.2
Revenue/Profit Sharing                0.2
Competitive Restriction Exception     0.2
Covenant Not To Sue                   0.2
Volume Restriction                    0.2
Price Restrictions                    0.4
Liquidated Damages                    0.4
Joint Ip Ownership                    0.4
Ip Ownership Assignment               0.4
Rofr/Rofo/Rofn                        0.6
Post-Termination Services             0.6
Non-Disparagement                     0.6
Non-Compete                           0.6
Warranty Duration                     0.6
Agreement Date                        0.6
Irrevocable Or Perpetual License      0.8
Unlimited/All-You-Can-Eat-License     0.8
Source Code Escrow                    0.8
Affiliate License-Licensor            0.8
Audit Rights                          0.8
Non-Transferable License              0.8
Cap On Liability                      0.8
Affiliate License-Licensee            0.8
No-Solicit Of Customers               0.8
Effective Date                        0.8
Expiration Date                       0.8
License Grant                         0.8
No-Solicit Of Employees               1.0
Notice Period To Terminate Renewal    1.0
Insurance                             1.0
Document Name                         1.0
Anti-Assignment                       1.0
Renewal Term                          1.0
Termination For Convenience           1.0
Third Party Beneficiary               1.0
Uncapped Liability                    1.0
Governing Law                         1.0
Change Of Control                     1.0
Parties                               1.0
Name: hit, dtype: float64

In [95]:
sentence_window_parser_6 = SentenceWindowNodeParser.from_defaults(
    window_size=6,
    window_metadata_key="window",
    original_text_metadata_key="original_text"
)

sentence_nodes_6 = sentence_window_parser_6.get_nodes_from_documents(sentence_documents)

counters = defaultdict(int)
for n in sentence_nodes_6:
    title = n.metadata["title"]
    n.metadata["chunk_index"] = counters[title]
    counters[title] += 1

print(f"nombre de phrases indexees: {len(sentence_nodes_6)}")

nombre de phrases indexees: 50675

In [96]:
vector_store_sentence_6 = QdrantVectorStore(
    collection_name="cuad_sentence_window6_hybrid",
    client=client,
    enable_hybrid=True,
    fastembed_sparse_model="Qdrant/bm25"
)
storage_context_sentence_6 = StorageContext.from_defaults(vector_store=vector_store_sentence_6)
index_sentence_6 = VectorStoreIndex(sentence_nodes_6, storage_context=storage_context_sentence_6, embed_model=nomic_embed)

In [97]:
def retrieve_scoped_sentence_window_6(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in sentence_nodes_6 if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.metadata.get("window", n.get_content()), "score": None} for n in selected]

    if tier == 3:
        retrieve_top_k = 15
        sparse_top_k = 15
        rerank_top_n = 5

    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)
    retrieved_nodes = metadata_replacer.postprocess_nodes(retrieved_nodes)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    return [{"text": n.get_content(), "score": n.score} for n in reranked_nodes]

In [98]:
sentence_window6_hit_rate, sentence_window6_hit_by_category, sentence_window6_df = compute_hit_rate_reranked(
    positive_sample, index_sentence_6, retrieve_fn=retrieve_scoped_sentence_window_6
)
print(f"Sentence-window (size=6) hit rate: {sentence_window6_hit_rate:.3f}")

Sentence-window (size=6) hit rate: 0.683

In [99]:
sentence_window6_hit_by_category

category
Minimum Commitment                    0.0
Most Favored Nation                   0.0
Revenue/Profit Sharing                0.2
Volume Restriction                    0.2
Exclusivity                           0.2
Rofr/Rofo/Rofn                        0.4
Price Restrictions                    0.4
Covenant Not To Sue                   0.4
Liquidated Damages                    0.4
Joint Ip Ownership                    0.4
Ip Ownership Assignment               0.4
Unlimited/All-You-Can-Eat-License     0.6
Post-Termination Services             0.6
Non-Compete                           0.6
Warranty Duration                     0.6
Cap On Liability                      0.6
Competitive Restriction Exception     0.6
Affiliate License-Licensee            0.8
Source Code Escrow                    0.8
Insurance                             0.8
Non-Transferable License              0.8
Non-Disparagement                     0.8
Audit Rights                          0.8
No-Solicit Of Employees               0.8
Third Party Beneficiary               0.8
Effective Date                        0.8
Expiration Date                       0.8
Affiliate License-Licensor            0.8
No-Solicit Of Customers               0.8
Agreement Date                        0.8
Termination For Convenience           1.0
Uncapped Liability                    1.0
Governing Law                         1.0
Renewal Term                          1.0
Parties                               1.0
Change Of Control                     1.0
Document Name                         1.0
License Grant                         1.0
Irrevocable Or Perpetual License      1.0
Anti-Assignment                       1.0
Notice Period To Terminate Renewal    1.0
Name: hit, dtype: float64

In [100]:
checkpoint["category_to_tier"] = category_to_tier
checkpoint["adaptive_hit_rate"] = adaptive_hit_rate
checkpoint["adaptive_hit_by_category"] = adaptive_hit_by_category
checkpoint["adaptive_df"] = adaptive_df

# pistes explorees et rejetees (documentation)
checkpoint["sentence_window_hit_rate"] = sentence_window_hit_rate
checkpoint["sentence_window6_hit_rate"] = sentence_window6_hit_rate

with open("../artifacts/baseline_v2_checkpoint.pkl", "wb") as f:
    pickle.dump(checkpoint, f)

print("Checkpoint mis a jour - meilleure config: 0.746 (chunking fixe + hybride + bge-reranker-large + top_k adaptatif)")

Checkpoint mis a jour - meilleure config: 0.746 (chunking fixe + hybride + bge-reranker-large + top_k adaptatif)

In [102]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
from llama_index.core.node_parser import LangchainNodeParser

lc_splitter = RecursiveCharacterTextSplitter(
    chunk_size=512,
    chunk_overlap=50,
    length_function=lambda text: len(tokenizer.encode(text)),
)

recursive_parser = LangchainNodeParser(lc_splitter)
recursive_nodes = recursive_parser.get_nodes_from_documents(sentence_documents)

counters = defaultdict(int)
for n in recursive_nodes:
    title=n.metadata["title"]
    n.metadata["chunk_index"] = counters[title]
    counters[title]+=1

print(f"nbre de chunks (recursive): {len(recursive_nodes)}")
print(f"moy de chunks par contrat: {len(recursive_nodes)/len(relevant_contracts):.1f}")

nbre de chunks (recursive): 9776
moy de chunks par contrat: 60.7

In [103]:
vector_store_recursive= QdrantVectorStore(
    collection_name="cuad_recursive_hybrid",
    client=client,
    enable_hybrid=True,
    fastembed_sparse_model="Qdrant/bm25"
)

storage_context_recursive = StorageContext.from_defaults(vector_store=vector_store_recursive)
index_recursive = VectorStoreIndex(recursive_nodes, storage_context=storage_context_recursive, embed_model=nomic_embed)

In [104]:
def retrieve_scoped_recursive(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in recursive_nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.get_content(), "score": None} for n in selected]

    if tier == 3:
        retrieve_top_k = 15
        sparse_top_k = 15
        rerank_top_n = 5

    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    return [{"text": n.get_content(), "score": n.score} for n in reranked_nodes]

In [105]:
recursive_hit_rate, recursive_hit_by_category, recursive_df = compute_hit_rate_reranked(
    positive_sample, index_recursive, retrieve_fn=retrieve_scoped_recursive
)
print(f"Recursive chunking hit rate: {recursive_hit_rate:.3f}")

Recursive chunking hit rate: 0.624

In [106]:
recursive_hit_by_category

category
Minimum Commitment                    0.0
Revenue/Profit Sharing                0.0
Most Favored Nation                   0.0
Ip Ownership Assignment               0.2
Volume Restriction                    0.2
Exclusivity                           0.2
Competitive Restriction Exception     0.2
Covenant Not To Sue                   0.2
Post-Termination Services             0.2
Rofr/Rofo/Rofn                        0.2
Liquidated Damages                    0.4
No-Solicit Of Customers               0.4
License Grant                         0.4
Non-Disparagement                     0.6
Non-Compete                           0.6
Price Restrictions                    0.6
Uncapped Liability                    0.6
Notice Period To Terminate Renewal    0.6
Warranty Duration                     0.6
Affiliate License-Licensor            0.6
Irrevocable Or Perpetual License      0.8
Unlimited/All-You-Can-Eat-License     0.8
Termination For Convenience           0.8
Source Code Escrow                    0.8
Agreement Date                        0.8
Joint Ip Ownership                    0.8
Cap On Liability                      0.8
Effective Date                        0.8
No-Solicit Of Employees               0.8
Insurance                             0.8
Non-Transferable License              0.8
Change Of Control                     1.0
Parties                               1.0
Document Name                         1.0
Audit Rights                          1.0
Renewal Term                          1.0
Anti-Assignment                       1.0
Expiration Date                       1.0
Third Party Beneficiary               1.0
Governing Law                         1.0
Affiliate License-Licensee            1.0
Name: hit, dtype: float64

In [107]:
def retrieve_scoped_recursive(title, question, category, index, retrieve_top_k=20, sparse_top_k=20, rerank_top_n=6):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in recursive_nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.get_content(), "score": None} for n in selected]

    if tier == 3:
        retrieve_top_k = 30
        sparse_top_k = 30
        rerank_top_n = 10

    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    return [{"text": n.get_content(), "score": n.score} for n in reranked_nodes]

In [108]:
allrecursive_hit_rate, allrecursive_hit_by_category, allrecursive_df = compute_hit_rate_reranked(
    positive_sample, index_recursive, retrieve_fn=retrieve_scoped_recursive
)
print(f"Recursive chunking hit rate: {allrecursive_hit_rate:.3f}")

Recursive chunking hit rate: 0.624

In [109]:
import random
random.seed(789)

sample_titles = random.sample([c["title"] for c in unique_contracts], 15)

for title in sample_titles:
    contract = next(c for c in unique_contracts if c["title"] == title)
    print("=" * 100)
    print(f"TITRE: {title}")
    print("-" * 100)
    print(contract["clean_context"][:1500])
    print()

====================================================================================================
TITRE: AURASYSTEMSINC_06_16_2010-EX-10.25-STRATEGIC ALLIANCE AGREEMENT
----------------------------------------------------------------------------------------------------
STRATEGIC ALLIANCE AGREEMENT This STRATEGIC ALLIANCE AGREEMENT (the "Agreement") is entered into as of March 18, 2010 (the "Effective Date"), between AURA SYSTEMS INC., a Delaware Corporation ("Aura") and ZANOTTI EAST INC., a Massachusetts Corporation ("Zanotti"). WHEREAS, Aura has invented, manufactures and distributes a unique, integrated electromagnetic mobile power generation system capable of delivering on-demand both AC and DC power for numerous end-uses, including without limitation, all-electric transport refrigeration (the "AuraGen"); WHEREAS, the AuraGen is the subject of substantial proprietary information, including but not limited to patents, trademarks, trade secrets, know-how, and confidential information owned by Aura; WHEREAS, Zanotti is a world-wide leading manufacturer and distributor of transport refrigeration systems and is desirous of expanding its market share within the United States, and WHEREAS, Zanotti and Aura are desirous of incorporating the AuraGen power system with various Zanotti transport refrigeration systems to be sold by Aura to end-users in the United States as an integrated all-electric transport refrigeration solution; NOW, THEREFORE, in consideration of their mutual covenants and obligations contained herein, and the mutual benefits to be derived herefrom, Aura and Zanotti (collectively the "Parties"), intending to be legally bound, do hereby covenant and agree as follows: Article 1: Definitions 1.1 The term "AETRU System" means an int

====================================================================================================
TITRE: ZtoExpressCaymanInc_20160930_F-1_EX-10.10_9752871_EX-10.10_Transportation Agreement
----------------------------------------------------------------------------------------------------
Exhibit 10.10 Road Transportation Agreement Party A (Shipper): ZTO Express Co., Ltd. Address: Building 1, No. 1685, Huazhi Road, Huaxin Twon, Qingpu District, Shanghai Party B (Carrier): Tonglu Tongze Logistics Ltd. Address: 12 Floor, HSBC Tower, Yinchun South Road, Tonglu County, Zhejiang Province Due to the need for logistics business, Party A and Party B enter into this Road Transportation Agreement (this "Agreement"), in which Party A pays the freight and Party B provides parcel transportation services to Party A. In accordance with relevant laws and regulations, Party A and Party B have sufficiently negotiated the specific matters and voluntarily reached the following Agreement based on equality, reciprocity and integrity. This Agreement is to be complied by both Parties. 1. Party B shall provide parcel transportation services on highway line-haul routes based on the needs of Party A. 2. Period of transportation services: this Agreement is valid for an indefinite term. Subsequent contracts might be entered in case of special business. 3. Freight and payment method: (a) Verification of freight: Party A pays freight based on carload rate (such freight includes pick-up charges, door-to-door delivery charges and tax fees). (b) Party A shall not pay any other charges other than the freight. (c) Clearance of freight: the clearance method is based on both Parties' fund clearance arrangement and the final clearance amount is subject to actual carriage amount and EX-warehouse ("E

====================================================================================================
TITRE: TheglobeComInc_19990503_S-1A_EX-10.20_5416126_EX-10.20_Co-Branding Agreement
----------------------------------------------------------------------------------------------------
EXHIBIT 10.20

CO-BRANDING Agreement

This Co-Branding Agreement (the "Agreement") is entered into as of March ___, 1999 (the "Effective Date") by and between theglobe.com, Inc., with its principal place of business at 31 West 21st Street, New York, NY 10010 ("theglobe"), and The Boxlot Company, with its principal place of business at 12626 High Bluff Drive, Suite 370, San Diego, CA 92130 ("Boxlot").

1. DEFINITIONS.

(a) "Boxlot Banners" means any banner, button, text or similar ads Boxlot provides to theglobe in connection with this Agreement.

(b) "Boxlot Content" means any content or information (including without limitation any text, music, sound, photographs, video, graphics, data or software), in any medium, provided by Boxlot to theglobe (other than Boxlot Banners), as part of the Service or on the Co-Branded Pages, including any content specified in Exhibit A.

(c) "Boxlot Marks" means all Boxlot domain names, trademarks, logos, and other graphics reasonably necessary or desirable for theglobe to perform under this Agreement.

(d) "Boxlot Site" means the Boxlot-branded (i.e., non-co-branded) version of the Service and associated pages.

(e) "Co-Branded Pages" means all pages of the Service (including, without limitation, any Java screens associated with the Service or emails or other direct communications sent to Users by operation of the Service).

(f) "Domain Name" means the domain name described in Exhibit A.

(g) "Launch Date" means the first date on which the Se

====================================================================================================
TITRE: Freecook_20180605_S-1_EX-10.3_11233807_EX-10.3_Hosting Agreement
----------------------------------------------------------------------------------------------------
By Client: /s/ Natalija Tunevic

Website Design, Development and Hosting Agreement

This Website Design, Development and Hosting Agreement the ("Agreement") is entered into on January 11, 2018 by and between Natalija Tunevic, director of FreeCook (hereinafter referred to as "Client") and Mitchell Vitalis, director of Mitchell's Web Advance, PLC (hereinafter referred to as "Company").

1. Website Design and Development. Client agrees to pay to Company the sum of $5,000 (the "Contract Price") to design and develop a website for Client (the "Client Website") in accordance with the accompanying Scope of Work, attached to this Agreement as Exhibit A.

(a) Change Orders. Any changes to the Scope of Work following the execution of this Agreement requiring Additional Work must be submitted to and accepted by Company in writing as a "Change Order". The costs of any such changes shall be added to the Contract Price. Additional Work shall be defined as the addition or revision of pages, graphics, or other features, any text, graphic or page design or programming requiring more than two rounds of textual or graphical revisions, substantial revisions to text and/or content provided by Client, changes to elements which have been finalized, or significant changes in the Scope of Work.

(b) Due Dates and Delays. Company will use its best efforts to deliver the Client Website in the time frame specified in the Scope of Work. Terms of the project: 12 weeks from February 8, 2018 to May 3, 2018.

====================================================================================================
TITRE: ROCKYMOUNTAINCHOCOLATEFACTORY,INC_12_23_2019-EX-10.2-STRATEGIC ALLIANCE AGREEMENT
----------------------------------------------------------------------------------------------------
Exhibit 10.2 PORTIONS OF THIS EXHIBIT MARKED BY [**] HAVE BEEN OMITTED PURSUANT TO RULE 601(B)(10) OF REGULATION S-K. THE OMITTED INFORMATION IS (I) NOT MATERIAL AND (II) WOULD LIKELY CAUSE COMPETITIVE HARM TO THE REGISTRANT IF PUBLICLY DISCLOSED. EXECUTION VERSION STRATEGIC ALLIANCE AGREEMENT STRATEGIC ALLIANCE AGREEMENT, dated as of December 20, 2019 (as amended, supplemented or otherwise modified from time to time, this "Agreement"), by and among Farids & Co. LLC, a Delaware limited liability company ("Farids"), Edible Arrangements, LLC, a Delaware limited liability company ("EA"), and Rocky Mountain Chocolate Factory, Inc., a Delaware corporation (the "Company"). W I T N E S S E T H: WHEREAS, the Company is an international franchisor, confectionery manufacturer and retail operator; WHEREAS, Farids is a holding company and, together with TF (as defined below), indirectly controls EA; WHEREAS, EA is a US-based franchisor that specializes in fresh fruit arrangements and specialty fruit gift items; WHEREAS, the Company desires to issue and sell, and Farids desires to purchase, 126,839 shares (the "Purchased Shares") of the Company's common stock, $0.001 par value per share (the "Common Stock"), on the terms set forth herein; WHEREAS, substantially concurrently with the execution and delivery of this Agreement, the Company and EA shall execute and deliver the Warrant (as defined below); WHEREAS, substantially concurrently with the execution and delivery of this Agreement, the

====================================================================================================
TITRE: INTERNATIONALFASTFOODCORP_04_04_1997-EX-99-FRANCHISE AGREEMENT
----------------------------------------------------------------------------------------------------
FRANCHISE AGREEMENT

TABLE OF CONTENTS

I. INTRODUCTION

II. AGREEMENT

1. Definitions

2. Franchise Grant; Term

2.1 Grant 2.2 Term 2.3 No Renewal Right: No Exclusivity 2.4 Continuous Operation 2.5 Best Efforts

3. Consideration for Franchise Grant

4. Management, Control and Corporate Documents of Franchisee

4.1 Managing Director 4.2 Director of Operations 4.3 Substitute Director of Operations 4.4 Restaurant Manager 4.5 Corporate Documents 4.5.1 Single Purpose Entity 4.5 2 Managing Director's Authority 4.5.3 Issuance and Transfer of Shares 4.5.4 Amendments

5. Standards and Uniformity 5.1 Strict Compliance 5.2 The MOD Manual 5.3 Building and Premises 5.3.1 Initial Construction 5 3 2 Repair and Maintenance 5 3.3 Current Image 5.4 Signs 5.5 Equipment 5.6 Vending Machines, Etc.

5 7 Menu Service and Hygiene 5.8 Hours of Operations 5.9 Uniforms 5.10 Advertising and Promotion Materials 5.11 Interference with Employment Relations of Others 5.12 Improvements 5.13 Self-Audit 5.14 Health Problems 5.15 Right of Entry, Inspection and Closure 5.16 Sources of Supply 5.16.1 Authorized Suppliers 5.16.2 Self-Supply 5.16.3 Limit on BKC Responsibility 5. 16.4 Franchisee's Responsibilities

6. Services to Franchisee

6.1 Services Provided By BKC 6.2 Services Not Provided By BKC 6.3 Optional Services

7. Location 7.1 Exclusive Purpose 7.2 Damage to Franchised Restaurant

8. Training and Staffing

8.1 Pre-Opening Training 8.2 New Director of Operations 8.3 Training Program

9. Royalty and Adve

====================================================================================================
TITRE: SFGFINANCIALCORP_05_12_2009-EX-10.1-SOFTWARE LICENSE AND MAINTENANCE AGREEMENT
----------------------------------------------------------------------------------------------------
SOFTWARE LICENSE AND MAINTENANCE AGREEMENT THIS SOFTWARE LICENSE AND MAINTENANCE AGREEMENT ("Agreement") is made and entered into as of this 27th day of April 2009 by and between SFG Financial Corp, a/k/a E-Path FX, a Delaware Corporation whose principal address is 575 Madison Avenue, 8th Floor, New York, NY 10022 ("Licensor"), and 551 FX IB Associates, LLC a Delaware Limited Liability Company, whose principal address is located at 575 Madison Avenue, 8th Floor, New York, NY 10022 ("Licensee"). WHEREAS, Licensor is the owner of a certain proprietary trading software known as the "E-Path FX Trading Platform", specifically, and variations thereof, along with documentation and related information, including the intellectual property rights pertaining thereto: and WHEREAS, Licensor is the owner of the computer equipment (the "Hardware") required for the operation of the Platform that is located at a single centralized location, specifically at Internap Inc,76 Ninth Avenue, New York, New York10011; and WHEREAS, Licensee desires to obtain from licensor a Non Exclusive, Non Transferrable license rights and licenses granted herein to the Platform, for purposes of implementing and marketing an over-the-counter, ("OTC") Foreign Currency Exchange Service utilizing the Platform; and WHEREAS, Licensor shall convey a Non Exclusive license to the Licensee solely for Licensee's use in the field of foreign exchange transactions only; and WHEREAS, Licensor is willing to grant such rights, lice

====================================================================================================
TITRE: ARMSTRONGFLOORING,INC_01_07_2019-EX-10.2-INTELLECTUAL PROPERTY AGREEMENT
----------------------------------------------------------------------------------------------------
Exhibit 10.2

Execution Version

INTELLECTUAL PROPERTY AGREEMENT

This INTELLECTUAL PROPERTY AGREEMENT (this "Agreement"), dated as of December 31, 2018 (the "Effective Date") is entered into by and between Armstrong Flooring, Inc., a Delaware corporation ("Seller") and AFI Licensing LLC, a Delaware limited liability company ("Licensing" and together with Seller, "Arizona") and AHF Holding, Inc. (formerly known as Tarzan HoldCo, Inc.), a Delaware corporation ("Buyer") and Armstrong Hardwood Flooring Company, a Tennessee corporation (the "Company" and together with Buyer the "Buyer Entities") (each of Arizona on the one hand and the Buyer Entities on the other hand, a "Party" and collectively, the "Parties").

WHEREAS, Seller and Buyer have entered into that certain Stock Purchase Agreement, dated November 14, 2018 (the "Stock Purchase Agreement"); WHEREAS, pursuant to the Stock Purchase Agreement, Seller has agreed to sell and transfer, and Buyer has agreed to purchase and acquire, all of Seller's right, title and interest in and to Armstrong Wood Products, Inc., a Delaware corporation ("AWP") and its Subsidiaries, the Company and HomerWood Hardwood Flooring Company, a Delaware corporation ("HHFC," and together with the Company, the "Company Subsidiaries" and together with AWP, the "Company Entities" and each a "Company Entity") by way of a purchase by Buyer and sale by Seller of the Shares, all upon the terms and condition set forth therein;

WHEREAS, Arizona owns certain Co

====================================================================================================
TITRE: INTERSECTENT,INC_05_11_2020-EX-10.1-SUPPLY AGREEMENT
----------------------------------------------------------------------------------------------------
Exhibit 10.1 [*] Certain confidential information contained in this document, marked by brackets, is omitted because it is both (i) not material and (ii) would be competitively harmful if publicly disclosed.

SUPPLY AGREEMENT

THIS SUPPLY AGREEMENT (this "Agreement") is made this, 20t h day of January, 2020 (the "Effective Date"), by and between HOVIONE INTER AG, together with its subsidiaries and affiliates, and organized and existing under the laws of Switzerland and having its registered office at Pilatusstrasse 23, CH-6003, Luzern, Switzerland (hereafter referred to as "HOVIONE"), and INTERSECT ENT, Inc. together with its subsidiaries and affiliates, and organized and existing under the laws of Delaware and having its registered office at 1555 Adams Drive, Menlo Park, CA 94025 (hereafter referred to as "INTERSECT"). HOVIONE and INTERSECT are each sometimes referred to herein as a "Party" and together as the "Parties."

WHEREAS, HOVIONE has developed and manufacturers the active pharmaceutical ingredient(s) identified in Exhibit A hereto (the "API"); and

WHEREAS, INTERSECT develops and markets Finished Product based on the API, as defined herein; and

WHEREAS, INTERSECT desires to acquire API from HOVIONE to incorporate into the Finished Product; and

WHEREAS, HOVIONE is willing to supply such API for INTERSECT's use, on the terms and conditions set forth in this Agreement.

NOW THEREFORE, in consideration of the promises and the mutual covenants set forth herein and for

====================================================================================================
TITRE: FIBROGENINC_10_01_2014-EX-10.11-COLLABORATION AGREEMENT
----------------------------------------------------------------------------------------------------
[ * ] = Certain confidential information contained in this document, marked by brackets, has been omitted and filed separately with the Securities and Exchange Commission pursuant to Rule 406 of the Securities Act of 1933, as amended. Exhibit 10.11 COLLABORATION AGREEMENT

BY AND BETWEEN

ASTELLAS PHARMA INC.

AND

FIBROGEN, INC. June 1, 2005

CONFIDENTIAL EXECUTION COPY TABLE OF CONTENTS ARTICLE 1 DEFINITIONS 1

1.1 "Actions" 1 1.2 "Affiliate" 1 1.3 "Astellas Indemnitees" 1 1.4 "Astellas Territory" 1 1.5 "Authorized Designee" 1 1.6 "Bridging Strategy" 1 1.7 "Bulk Product" 2 1.8 "Commercialize" 2 1.9 "Completion" 2 1.10 "Confidential Information" 2 1.11 "Control" or "Controlled" 2 1.12 "Controlling Party" 2 1.13 "Data" 2 1.14 "Delivery" or "Delivered" 2 1.15 "Development Plan" 2 1.16 "Development Program" 2 1.17 "Enforcement Action" 2 1.18 "Event" 2 1.19 "Expanded Field" 2 1.20 "Expenses" 2 1.21 "FDA" 2 1.22 "FG Acquired Patents" 3 1.23 "FG Development Program" 3 1.24 "FG Indemnitees" 3 1.25 "FG Technology" 3 1.26 "FG Patents" 3 1.27 "FG Technical Information" 3 1.28 "FG Territory" 3 1.29 "Field" 4 1.30 "First Commercial Sale" 4 1.31 "Force Majeure Event" 4 1.32 "Fully Burdened Costs" 4 1.33 "Future Third Party Intellectual Property" 4 1.34 "GMP Guidelines" 4 1.35 "[ * ]" 4 1.36 "[ * ] Percentage" 5 1.37 "HIF" 5 -i-

[ * ] = Certain confidential information contained in this document, marked by brackets, has been omitted and filed separately with the Securities and Exchange C

====================================================================================================
TITRE: CERES,INC_01_25_2012-EX-10.20-Collaboration Agreement
----------------------------------------------------------------------------------------------------
Exhibit 10.20

Pages where confidential treatment has been requested are stamped 'Confidential Treatment Requested and the Redacted Material has been separately filed with the Commission,' and the confidential section has been marked as follows: [***].

Collaboration Agreement

between

Institute of Grassland and Environmental Research

and

Ceres, Inc. CERES-IGER Collaboration Agreement Page 1 of 75

TABLE OF CONTENTS 1. RESEARCH PROJECTS 3 2. MANAGEMENT COMMITTEE 7 3. EXCLUSIVITY 8 4. INTELLECTUAL PROPERTY 11 5. USE AND COMMERCIALIZATION RIGHTS 14 6. ENFORCEMENT OF JOINT INTELLECTUAL PROPERTY RIGHTS 16 7. CONFIDENTIALITY 16 8. PUBLICATIONS 18 9. PUBLICITY 18 10. RECORDS AND AUDITS 19 11. INDEPENDENT CONTRACTOR 19 12. CONVENTION ON BIOLOGICAL DIVERSITY 19 13. WARRANTIES 20 14. TERM AND TERMINATION 23 15. DISPUTE RESOLUTION AND APPLICABLE LAW 25 16. NOTICES 26 17. GENERAL 27 18. SPECIAL CONDITIONS IN CONNECTION WITH DEFRA AGREEMENT NF 0426 28 EXHIBIT A 30 DEFINITION OF COLLABORATION CROPS 30 EXHIBIT B 31 PREFERRED FORM OF RECEIPT FORM 31 EXHIBIT C 32 PREFERRED FORMS OF VARIETY EVALUATION AGREEMENT 32 EXHIBIT D 50 EXTERNAL FUNDING EXHIBIT E 50 51

EXISTING AGREEMENTS 51 EXHIBIT F 56 PRODUCTION AND COMMERCIALIZATION ACTIVITIES 56 EXHIBIT G 57 MODEL LICENSE AGREEMENT FOR NON-TRANSGENIC VARIETIES / NON-UK 57 EXHIBIT H 74 CERTAIN REMUNERATION PRINCIPLES 74 CERES-IGER Collaboration Agreement Page 2 of 75

COLLABORATION AGREEMENT

THIS AGREEMENT is made this 1st day of April, 2007 (

====================================================================================================
TITRE: NEOMEDIATECHNOLOGIESINC_12_15_2005-EX-16.1-DISTRIBUTOR AGREEMENT
----------------------------------------------------------------------------------------------------
Exhibit 16.1

AUTOMOTIVE REFINISH DISTRIBUTOR AGREEMENT (P.R.China)


In [110]:
checkpoint["recursive_hit_rate"] = recursive_hit_rate
checkpoint["recursive_hit_by_category"] = recursive_hit_by_category
checkpoint["recursive_df"] = recursive_df

checkpoint["sentence_window_hit_by_category"] = sentence_window_hit_by_category
checkpoint["sentence_window_df"] = sentence_window_df

checkpoint["sentence_window6_hit_by_category"] = sentence_window6_hit_by_category
checkpoint["sentence_window6_df"] = sentence_window6_df

with open("../artifacts/baseline_v2_checkpoint.pkl", "wb") as f:
    pickle.dump(checkpoint, f)

print("Checkpoint complet sauvegarde avant pause.")

Checkpoint complet sauvegarde avant pause.

In [1]:
import pickle
with open("../artifacts/baseline_v2_checkpoint.pkl", "rb") as f:
    checkpoint = pickle.load(f)
for key, value in checkpoint.items():
    globals()[key] = value
print("Checkpoint recharge:", list(checkpoint.keys()))

Checkpoint recharge: ['baseline_hit_rate', 'baseline_hit_vy_category', 'baseline_df', 'bge_large_hit_rate', 'bge_large_hit_vy_category', 'bge_large_df', 'nomic_hit_rate', 'nomic_hit_vy_category', 'nomic_df', 'e5_hit_rate', 'e5_hit_by_category', 'e5_df', 'hybrid_hit_rate', 'hybrid_hit_by_category', 'hybrid_df', 'reranked_hit_rate', 'reranked_hit_by_category', 'reranked_df', 'merged', 'positive_sample', 'negative_sample', 'category_to_tier', 'reranked_large_short_hit_rate', 'reranked_large_short_hit_by_category', 'reranked_large_short_df', 'positive_large_short_scores_df', 'negative_large_short_scores_df', 'adaptive_hit_rate', 'adaptive_hit_by_category', 'adaptive_df', 'sentence_window_hit_rate', 'sentence_window6_hit_rate', 'recursive_hit_rate', 'recursive_hit_by_category', 'recursive_df', 'sentence_window_hit_by_category', 'sentence_window_df', 'sentence_window6_hit_by_category', 'sentence_window6_df']

In [2]:
from qdrant_client import QdrantClient
from llama_index.embeddings.ollama import OllamaEmbedding
from llama_index.vector_stores.qdrant import QdrantVectorStore
from llama_index.core import VectorStoreIndex

client = QdrantClient(path="../artifacts/qdrant_storage")
nomic_embed = OllamaEmbedding(model_name="nomic-embed-text")

vector_store_hybrid = QdrantVectorStore(
    collection_name="cuad_nomic_bm25_hybrid",
    client=client,
    enable_hybrid=True,
    fastembed_sparse_model="Qdrant/bm25",
)
index_hybrid = VectorStoreIndex.from_vector_store(vector_store_hybrid, embed_model=nomic_embed)

/Users/aitbellalhamza/Desktop/RAG-for-contract-understanding-CUAD/.cuad-venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/var/folders/2d/1h410ps12gn5kw05_3p23qpc0000gn/T/ipykernel_2599/1507995236.py:6: UserWarning: Local mode is not recommended for collections with more than 20,000 points. Collection <cuad_sentence_widow_hybrid> contains 50675 points. Consider using Qdrant in Docker or Qdrant Cloud for better performance with large datasets.
  client = QdrantClient(path="../artifacts/qdrant_storage")
/var/folders/2d/1h410ps12gn5kw05_3p23qpc0000gn/T/ipykernel_2599/1507995236.py:6: UserWarning: Local mode is not recommended for collections with more than 20,000 points. Collection <cuad_sentence_window6_hybrid> contains 50675 points. Consider using Qdrant in Docker or Qdrant Cloud for better performance with large datasets.
  client = QdrantClient(path="../artifacts/qdrant_storage")
Fetching 18 files: 100%|██████████| 18/18 [00:01<00:00, 12.56it/s]

In [8]:
from datasets import load_dataset, concatenate_datasets

dataset = load_dataset("theatticusproject/cuad-qa", revision="refs/convert/parquet")
train_data = dataset["train"]
test_data = dataset["test"]
print(len(train_data))
print(len(test_data))

22450
4182

In [9]:
full_data = concatenate_datasets([train_data, test_data])

In [10]:
seen_titles = set()
unique_contracts = []

for row in full_data:
    if row["title"] not in seen_titles:
        seen_titles.add(row["title"])
        unique_contracts.append({
            "title": row["title"],
            "context": row["context"]
        })
print(f"Number of unique contracts: {len(unique_contracts)}")

Number of unique contracts: 510

In [11]:
import re

def clean_contract_text(text: str) -> str:

    text = re.sub(r"[ \t]{2,}", " ", text)

    text = re.sub(r"\n{3,}", "\n\n", text)

    text = "\n".join(line.strip() for line in text.split('\n'))

    return text.strip()

In [12]:
for c in unique_contracts:
    c["clean_context"] = clean_contract_text(c["context"])

In [13]:
for item in positive_sample:
    item["ground_truth_clean"] = [clean_contract_text(a) for a in item["ground_truth"]]

In [14]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("BAAI/bge-small-en-v1.5")

In [15]:
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core import Document
from collections import defaultdict

CHUNK_SIZE = 512
CHUNK_OVERLAP = 50

Splitter = SentenceSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    tokenizer=tokenizer.encode
)

documents = [
    Document(
        text=c["clean_context"], metadata={"title": c["title"]})
        for c in unique_contracts
]

nodes = Splitter.get_nodes_from_documents(documents)

# chunk index for each contract
counters = defaultdict(int)
for n in nodes:
    title = n.metadata["title"]
    n.metadata["chunk_index"] = counters[title]
    counters[title] += 1

print(f"Number of contracts : {len(documents)}")
print(f"Number of chunks: {len(nodes)}")
print(f"Average chunks per contract: {len(nodes)/len(documents):.1f}")

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (7558 > 512). Running this sequence through the model will result in indexing errors

Number of contracts : 510
Number of chunks: 14230
Average chunks per contract: 27.9

In [16]:
from llama_index.core.postprocessor import SentenceTransformerRerank
reranker = SentenceTransformerRerank(model="BAAI/bge-reranker-large", top_n=3)

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 4725.32it/s]

In [17]:
from llama_index.core.vector_stores import MetadataFilters, ExactMatchFilter
import re

def strip_boilerplate(question):
    match = re.search(r'"([^"]+)"', question)
    category_quoted = match.group(0) if match else ""
    details = question.split("Details: ", 1)[1] if "Details: " in question else ""
    return f"{category_quoted}. {details}".strip()

def retrieve_scoped_reranked_adaptive_topk(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.get_content(), "score": None} for n in selected]

    if tier == 3:
        retrieve_top_k = 15
        sparse_top_k = 15
        rerank_top_n = 5

    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    return [{"text": n.get_content(), "score": n.score} for n in reranked_nodes]

In [18]:
from llama_index.core import PromptTemplate

qa_prompt_template = PromptTemplate(
    "Context information from the contract is below.\n"
    "---------------------\n"
    "{context_str}\n"
    "---------------------\n"
    "You are a contract review assistant analyzing one contract.\n"
    "Follow these steps:\n"
    "1. Decide whether the context above contains information relevant to the question. "
    "A relevant answer can be a full sentence, a clause, a heading, a title, a date, or a list of names "
    "— not only complete grammatical sentences.\n"
    "2. Do not treat a bare section heading or title (with no accompanying clause text) as an answer just "
    "because it resembles the category name in the question. However, if the context contains actual clause "
    "text — obligations, rights, restrictions, or definitions — that addresses what the question's \"Details\" "
    "describes, that IS valid evidence: quote it normally. Only treat something as \"not present\" when there "
    "is no clause text addressing the details, not merely because a heading happens to be present.\n"
    "3. If the question asks about the Document Name (the name/title of the contract), the answer is "
    "typically a short heading (2-6 words, often in ALL CAPS) located at the very beginning of the context "
    "— either the very first line, or the line immediately following an \"Exhibit X.X\" reference or a "
    "confidentiality/legal notice. Answer with ONLY this short title, do not include the surrounding "
    "paragraphs, recitals, or signature blocks.\n"
    "4. If the question asks about a specific date (such as Agreement Date or Effective Date), answer "
    "ONLY with the explicit date mentioned in a sentence that clearly labels it as such (e.g. \"the Effective Date\", "
    "\"dated as of\"). Do not infer a date from unrelated clauses such as renewal terms, option expirations, "
    "or other unrelated dates.\n"
    "5. Otherwise, if relevant information exists, respond with ONLY the exact text from the context that "
    "answers the question. Quote it directly. Do not paraphrase, do not add explanations or recommendations.\n"
    "6. If nothing in the context is relevant to the question, respond with EXACTLY the following sentence, "
    "word for word, with no rephrasing or additions: \"This clause is not present in this contract.\"\n"
    "Never combine both — give exactly one of the two response types above (step 5 or step 6), never a mix.\n"
    "Question: {query_str}\n"
    "Answer: "
)

In [19]:
from llama_index.llms.ollama import Ollama
llm = Ollama(model="llama3.2:3b", request_timeout=180, temperature=0.0)

In [20]:
def generate_answer(title, question, category):
    retrieved = retrieve_scoped_reranked_adaptive_topk(title, question, category, index_hybrid)
    contexts = [r["text"] for r in retrieved]
    context_str = "\n\n".join(contexts)
    prompt = qa_prompt_template.format(context_str=context_str, query_str=question)
    response = llm.complete(prompt)
    return str(response), contexts

In [21]:
from tqdm import tqdm
import json

def run_generation(sample, is_positive, output_path):
    results = []
    for item in tqdm(sample):
        try:
            answer, contexts = generate_answer(item["title"], item["question"], item["category"])
        except Exception as e:
            answer = f"[ERROR: {type(e).__name__}: {e}]"
            contexts = []

        result = {
            "title": item["title"],
            "category": item["category"],
            "tier": category_to_tier.get(item["category"], 2),
            "question": item["question"],
            "answer": answer,
            "contexts": contexts,
            "is_positive": is_positive,
        }
        if is_positive:
            result["ground_truth"] = " ".join(item["ground_truth_clean"])
        else:
            result["ground_truth"] = "This clause is not present in this contract."

        results.append(result)
        with open(output_path, "w") as f:
            json.dump(results, f, indent=2)
    return results

In [22]:
positive_results_v2 = run_generation(positive_sample, is_positive=True, output_path="../artifacts/positive_results_v2.json")
print(f"saved {len(positive_results_v2)} positive results.")

 19%|█▉        | 39/205 [13:44<1:17:43, 28.09s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xad3d0c000>
    label = <none>
    device = <AGXG13XDevice: 0x103dd7610>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x103dd9ad0>
        label = <none>
        device = <AGXG13XDevice: 0x103dd7610>
            name = Apple M1 Pro
    retainedReferences = 1
 36%|███▌      | 73/205 [29:17<1:01:46, 28.08s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xad3d0c000>
    label = <none>
    device = <AGXG13XDevice: 0x103dd7610>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x103dd9ad0>
        label = <none>
        device = <AGXG13XDevice: 0x103dd7610>
            name = Apple M1 Pro
    retainedReferences = 1
 48%|████▊     | 99/205 [43:34<52:41, 29.82s/it]  Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xad3d0c000>
    label = <none>
    device = <AGXG13XDevice: 0x103dd7610>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x103dd9ad0>
        label = <none>
        device = <AGXG13XDevice: 0x103dd7610>
            name = Apple M1 Pro
    retainedReferences = 1
 59%|█████▊    | 120/205 [59:29<1:06:09, 46.70s/it] Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xad3d0c000>
    label = <none>
    device = <AGXG13XDevice: 0x103dd7610>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x103dd9ad0>
        label = <none>
        device = <AGXG13XDevice: 0x103dd7610>
            name = Apple M1 Pro
    retainedReferences = 1
 63%|██████▎   | 130/205 [1:04:52<42:17, 33.83s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xad3d0c000>
    label = <none>
    device = <AGXG13XDevice: 0x103dd7610>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x103dd9ad0>
        label = <none>
        device = <AGXG13XDevice: 0x103dd7610>
            name = Apple M1 Pro
    retainedReferences = 1
 89%|████████▉ | 182/205 [1:35:44<12:30, 32.61s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xad3d0c000>
    label = <none>
    device = <AGXG13XDevice: 0x103dd7610>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x103dd9ad0>
        label = <none>
        device = <AGXG13XDevice: 0x103dd7610>
            name = Apple M1 Pro
    retainedReferences = 1
100%|██████████| 205/205 [1:50:07<00:00, 32.23s/it]

saved 205 positive results.

In [23]:
positive_results_v2_clean = [r for r in positive_results_v2 if not r["answer"].startswith("[ERROR")]
print(f"{len(positive_results_v2_clean)} usable after removing errors ({len(positive_results_v2) - len(positive_results_v2_clean)} errors)")

ragas_data = [
    {
        "user_input": item["question"],
        "response": item["answer"],
        "retrieved_contexts": item["contexts"],
        "reference": item["ground_truth"],
    }
    for item in positive_results_v2_clean
]

205 usable after removing errors (0 errors)

In [28]:
from dotenv import load_dotenv
load_dotenv(override=True)

from langchain_anthropic import ChatAnthropic
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LlamaIndexEmbeddingsWrapper
from ragas.embeddings import LlamaIndexEmbeddingsWrapper

class ChatAnthropicNoTemp(ChatAnthropic):
    def __setattr__(self, name, value):
        if name == "temperature":
            return
        super().__setattr__(name, value)

claude_llm = ChatAnthropicNoTemp(model="claude-haiku-4-5", max_tokens=4096)
ragas_llm_claude = LangchainLLMWrapper(claude_llm)
ragas_embeddings = LlamaIndexEmbeddingsWrapper(nomic_embed)

In [29]:
from ragas.metrics import faithfulness, answer_correctness, answer_relevancy, context_precision, context_recall
from ragas.run_config import RunConfig

metrics = [faithfulness, answer_relevancy, context_precision, context_recall, answer_correctness]
run_config_claude = RunConfig(timeout=180, max_workers=4)

In [32]:
from ragas import EvaluationDataset, evaluate
import json, time, os

BATCH_SIZE = 20
output_path = "../artifacts/ragas_scores_v2.json"

if os.path.exists(output_path):
    with open(output_path) as f:
        all_scores = json.load(f)
else:
    all_scores = []

start_index = len(all_scores)
n_batches = (len(ragas_data) - 1) // BATCH_SIZE + 1

for i in range(start_index, len(ragas_data), BATCH_SIZE):
    batch = ragas_data[i : i + BATCH_SIZE]
    batch_dataset = EvaluationDataset.from_list(batch)
    print(f"batch {i // BATCH_SIZE + 1}/{n_batches} ({len(batch)} examples)...")

    result = evaluate(dataset=batch_dataset, metrics=metrics, llm=ragas_llm_claude,
                       embeddings=ragas_embeddings, run_config=run_config_claude)

    all_scores.extend(result.to_pandas().to_dict(orient="records"))
    with open(output_path, "w") as f:
        json.dump(all_scores, f, indent=2)
    print(f" -> saved ({len(all_scores)}/{len(ragas_data)})")

In [33]:
import json
import pandas as pd

with open("../artifacts/ragas_scores_v2.json") as f:
    all_scores = json.load(f)

df_check = pd.DataFrame(all_scores)
metric_cols = ["faithfulness", "answer_relevancy", "context_precision", "context_recall", "answer_correctness"]

failed_indices = df_check[df_check[metric_cols].isna().any(axis=1)].index.tolist()
print(f"Nombre d'exemples a refaire: {len(failed_indices)}")

Nombre d'exemples a refaire: 22

In [35]:
retry_data = [
    {
        "user_input": all_scores[i]["user_input"],
        "response": all_scores[i]["response"],
        "retrieved_contexts": all_scores[i]["retrieved_contexts"],
        "reference": all_scores[i]["reference"],
    }
    for i in failed_indices
]

retry_dataset = EvaluationDataset.from_list(retry_data)
retry_result = evaluate(
    dataset=retry_dataset,
    metrics=metrics,
    llm=ragas_llm_claude,
    embeddings=ragas_embeddings,
    run_config=run_config_claude,
)
retry_scores = retry_result.to_pandas().to_dict(orient="records")

Evaluating:   8%|▊         | 9/110 [00:36<06:22,  3.79s/it]Exception raised in Job[4]: LLMDidNotFinishException(The LLM generation was not completed. Please increase the max_tokens and try again.)
Evaluating:  25%|██▍       | 27/110 [01:35<04:27,  3.22s/it]Exception raised in Job[14]: LLMDidNotFinishException(The LLM generation was not completed. Please increase the max_tokens and try again.)
Evaluating: 100%|██████████| 110/110 [05:12<00:00,  2.84s/it]

In [36]:
for idx, new_row in zip(failed_indices, retry_scores):
    all_scores[idx].update(new_row)

with open("../artifacts/ragas_scores_v2.json", "w") as f:
    json.dump(all_scores, f, indent=2)

df_check2 = pd.DataFrame(all_scores)
print("NaN restants par metrique:")
print(df_check2[metric_cols].isna().sum())

NaN restants par metrique:
faithfulness          0
answer_relevancy      0
context_precision     0
context_recall        0
answer_correctness    2
dtype: int64

In [37]:
for score_row, meta_row in zip(all_scores, positive_results_v2_clean):
    score_row["category"] = meta_row["category"]
    score_row["tier"] = meta_row["tier"]

df_scores_v2 = pd.DataFrame(all_scores)
metric_cols = ["faithfulness", "answer_relevancy", "context_precision", "context_recall", "answer_correctness"]

summary_global_v2 = df_scores_v2[metric_cols].mean().to_frame(name="moyenne_v2")
print(summary_global_v2)

summary_by_category_v2 = df_scores_v2.groupby("category")[metric_cols].mean()
summary_global_v2.to_csv("../artifacts/ragas_scores_v2_summary_global.csv")
summary_by_category_v2.to_csv("../artifacts/ragas_scores_v2_summary_by_category.csv")

                    moyenne_v2
faithfulness          0.784636
answer_relevancy      0.573797
context_precision     0.366064
context_recall        0.474936
answer_correctness    0.393670

In [38]:
df_scores_v2["was_widened"] = df_scores_v2["category"].apply(lambda c: category_to_tier.get(c, 2) == 3)
comparison = df_scores_v2.groupby("was_widened")[metric_cols].mean()
print(comparison)

             faithfulness  answer_relevancy  context_precision  \
was_widened
False            0.785594          0.574299           0.377604
True             0.781230          0.572014           0.325031

             context_recall  answer_correctness
was_widened
False              0.445699            0.401436
True               0.578889            0.366404

In [39]:
def extract_all_chunk_scores(sample, index, retrieve_fn=retrieve_scoped_reranked_adaptive_topk):
    rows = []
    for item in sample:
        title = item["title"]
        question = item["question"]
        category = item["category"]
        tier = category_to_tier.get(category, 2)

        retrieved = retrieve_fn(title, question, category, index)

        for position, r in enumerate(retrieved, start=1):
            rows.append({
                "title": title,
                "category": category,
                "tier": tier,
                "position": position,
                "score": r["score"],
            })
    return pd.DataFrame(rows)

In [40]:
positive_chunk_scores_df = extract_all_chunk_scores(positive_sample, index_hybrid)
positive_chunk_scores_df["is_positive"] = True

negative_chunk_scores_df = extract_all_chunk_scores(negative_sample, index_hybrid)
negative_chunk_scores_df["is_positive"] = False

all_chunk_scores_df = pd.concat([positive_chunk_scores_df, negative_chunk_scores_df], ignore_index=True)

In [41]:
all_chunk_scores_df.to_pickle("../artifacts/all_chunk_scores_v2.pkl")
print(f"Sauvegarde : {len(all_chunk_scores_df)} lignes (une par chunk x position)")

Sauvegarde : 1074 lignes (une par chunk x position)

In [42]:
summary_by_position = (
    all_chunk_scores_df.dropna(subset=["score"])
    .groupby(["position", "is_positive"])["score"]
    .describe()
)
print(summary_by_position)

                      count      mean       std       min       25%       50%  \
position is_positive
1        False        117.0  0.005376  0.014560  0.000077  0.000240  0.000813
         True         195.0  0.054134  0.127143  0.000100  0.000742  0.003682
2        False        114.0  0.001939  0.005140  0.000082  0.000191  0.000441
         True         194.0  0.009234  0.032343  0.000084  0.000385  0.000902
3        False        111.0  0.001095  0.002249  0.000079  0.000152  0.000348
         True         194.0  0.003976  0.013556  0.000084  0.000275  0.000533
4        False         24.0  0.000487  0.000537  0.000078  0.000131  0.000352
         True          45.0  0.003606  0.008892  0.000081  0.000185  0.000374
5        False         24.0  0.000352  0.000386  0.000077  0.000121  0.000223
         True          45.0  0.002329  0.005977  0.000081  0.000157  0.000321

                           75%       max
position is_positive
1        False        0.003190  0.099331
         True         0.033293  0.786843
2        False        0.001224  0.040945
         True         0.003317  0.273623
3        False        0.000835  0.014066
         True         0.001777  0.145077
4        False        0.000566  0.002026
         True         0.001481  0.051557
5        False        0.000401  0.001845
         True         0.001323  0.029929

In [43]:
POSITION_THRESHOLDS = {
    2: 0.00029,
    3: 0.00025,
    4: 0.00066,
    5: 0.00096,
}

def retrieve_scoped_reranked_threshold(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.get_content(), "score": None} for n in selected]

    if tier == 3:
        retrieve_top_k = 15
        sparse_top_k = 15
        rerank_top_n = 5

    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    kept = []
    for position, n in enumerate(reranked_nodes, start=1):
        if position == 1:
            kept.append({"text": n.get_content(), "score": n.score})
        elif n.score is not None and n.score >= POSITION_THRESHOLDS.get(position, float("inf")):
            kept.append({"text": n.get_content(), "score": n.score})

    return kept

In [46]:
def compute_hit_rate_reranked(sample, index, retrieve_fn=retrieve_scoped_reranked_threshold, rerank_top_n=3):
    results = []
    for item in sample:
        title = item["title"]
        question = item["question"]
        category = item["category"]
        reference_answers = item["ground_truth"]

        retrieved = retrieve_fn(title, question, category, index, rerank_top_n=rerank_top_n)
        retrieved_texts = [r["text"] for r in retrieved]
        retrieved_scores = [r["score"] for r in retrieved]

        hit = is_hit(reference_answers, retrieved_texts)

        results.append({
            "title": title,
            "category": category,
            "question": question,
            "hit": hit,
            "retrieved_chunks": retrieved_texts,
            "retrieved_scores": retrieved_scores,
        })

    df_hits = pd.DataFrame(results)
    overall_hit_rate = df_hits["hit"].mean()
    hit_rate_by_category = df_hits.groupby("category")["hit"].mean().sort_values()
    return overall_hit_rate, hit_rate_by_category, df_hits

In [48]:
import re
import pandas as pd

def normalize_text(text):
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    text = text.strip()
    return text

def is_hit(reference_answers, retrieved_chunks):
    normalized_chunks = [normalize_text(chunk) for chunk in retrieved_chunks]
    for ref in reference_answers:
        normalized_ref = normalize_text(ref)
        if not normalized_ref:
            continue
        for chunk in normalized_chunks:
            if normalized_ref in chunk:
                return 1
        
    return 0

def compute_hit_rate(sample, index, top_k=3):
    results = []
    for item in sample:
        title = item["title"]
        question = item["question"]
        category = item["category"]
        reference_answers = item["ground_truth"]

        retrieved_chunks = retrieve_scoped_generic(title, question, category, index, top_k=top_k)
        hit = is_hit(reference_answers, retrieved_chunks)

        results.append({"title": title, "category": category, "question": question, "hit": hit})

    
    df_hits = pd.DataFrame(results)
    overall_hit_rate = df_hits["hit"].mean()
    hit_rate_by_category = df_hits.groupby("category")["hit"].mean().sort_values()
    return overall_hit_rate, hit_rate_by_category, df_hits

In [49]:
threshold_hit_rate, threshold_hit_by_category, threshold_df = compute_hit_rate_reranked(
    positive_sample, index_hybrid, retrieve_fn=retrieve_scoped_reranked_threshold
)
print(f"Retrieval avec filtrage par seuil: {threshold_hit_rate:.3f}")

Retrieval avec filtrage par seuil: 0.663

In [50]:
print(threshold_hit_by_category)

category
Minimum Commitment                    0.0
Revenue/Profit Sharing                0.0
Rofr/Rofo/Rofn                        0.2
Most Favored Nation                   0.2
Exclusivity                           0.2
Volume Restriction                    0.4
No-Solicit Of Customers               0.4
Non-Compete                           0.4
Covenant Not To Sue                   0.4
Competitive Restriction Exception     0.4
Price Restrictions                    0.4
Ip Ownership Assignment               0.4
Liquidated Damages                    0.4
Non-Disparagement                     0.6
Non-Transferable License              0.6
Post-Termination Services             0.6
Unlimited/All-You-Can-Eat-License     0.6
Warranty Duration                     0.6
Cap On Liability                      0.8
Affiliate License-Licensor            0.8
Termination For Convenience           0.8
Source Code Escrow                    0.8
Agreement Date                        0.8
Audit Rights                          0.8
Joint Ip Ownership                    0.8
Notice Period To Terminate Renewal    0.8
Affiliate License-Licensee            0.8
Effective Date                        0.8
Expiration Date                       0.8
Insurance                             0.8
Irrevocable Or Perpetual License      0.8
Document Name                         1.0
Parties                               1.0
No-Solicit Of Employees               1.0
Renewal Term                          1.0
Anti-Assignment                       1.0
Governing Law                         1.0
Third Party Beneficiary               1.0
Uncapped Liability                    1.0
Change Of Control                     1.0
License Grant                         1.0
Name: hit, dtype: float64

In [51]:
comparison_hit = pd.DataFrame({
    "sans_filtrage_0.746": adaptive_hit_by_category,
    "avec_filtrage_0.663": threshold_hit_by_category,
})
comparison_hit["delta"] = comparison_hit["avec_filtrage_0.663"] - comparison_hit["sans_filtrage_0.746"]
print(comparison_hit.sort_values("delta").to_string())

                                    sans_filtrage_0.746  avec_filtrage_0.663  delta
category
Price Restrictions                                  1.0                  0.4   -0.6
Non-Compete                                         1.0                  0.4   -0.6
Rofr/Rofo/Rofn                                      0.6                  0.2   -0.4
Non-Transferable License                            0.8                  0.6   -0.2
Warranty Duration                                   0.8                  0.6   -0.2
Revenue/Profit Sharing                              0.2                  0.0   -0.2
Exclusivity                                         0.4                  0.2   -0.2
Termination For Convenience                         1.0                  0.8   -0.2
Ip Ownership Assignment                             0.6                  0.4   -0.2
Audit Rights                                        1.0                  0.8   -0.2
No-Solicit Of Customers                             0.6                  0.4   -0.2
Volume Restriction                                  0.6                  0.4   -0.2
Renewal Term                                        1.0                  1.0    0.0
Post-Termination Services                           0.6                  0.6    0.0
Third Party Beneficiary                             1.0                  1.0    0.0
Notice Period To Terminate Renewal                  0.8                  0.8    0.0
Source Code Escrow                                  0.8                  0.8    0.0
Uncapped Liability                                  1.0                  1.0    0.0
Non-Disparagement                                   0.6                  0.6    0.0
Unlimited/All-You-Can-Eat-License                   0.6                  0.6    0.0
No-Solicit Of Employees                             1.0                  1.0    0.0
Parties                                             1.0                  1.0    0.0
Affiliate License-Licensee                          0.8                  0.8    0.0
Liquidated Damages                                  0.4                  0.4    0.0
Affiliate License-Licensor                          0.8                  0.8    0.0
Agreement Date                                      0.8                  0.8    0.0
Anti-Assignment                                     1.0                  1.0    0.0
Cap On Liability                                    0.8                  0.8    0.0
Change Of Control                                   1.0                  1.0    0.0
Competitive Restriction Exception                   0.4                  0.4    0.0
Covenant Not To Sue                                 0.4                  0.4    0.0
Document Name                                       1.0                  1.0    0.0
Effective Date                                      0.8                  0.8    0.0
Expiration Date                                     0.8                  0.8    0.0
Governing Law                                       1.0                  1.0    0.0
Insurance                                           0.8                  0.8    0.0
Irrevocable Or Perpetual License                    0.8                  0.8    0.0
Joint Ip Ownership                                  0.8                  0.8    0.0
License Grant                                       1.0                  1.0    0.0
Most Favored Nation                                 0.2                  0.2    0.0
Minimum Commitment                                  0.0                  0.0    0.0

In [52]:
POSITION_THRESHOLDS_SOFT = {
    2: 0.00029,
    3: 0.00020,
    4: 0.00012,
    5: 0.00011,
}

def retrieve_scoped_reranked_threshold_soft(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.get_content(), "score": None} for n in selected]

    if tier == 3:
        retrieve_top_k = 15
        sparse_top_k = 15
        rerank_top_n = 5

    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    kept = []
    for position, n in enumerate(reranked_nodes, start=1):
        if position == 1:
            kept.append({"text": n.get_content(), "score": n.score})
        elif n.score is not None and n.score >= POSITION_THRESHOLDS_SOFT.get(position, float("inf")):
            kept.append({"text": n.get_content(), "score": n.score})

    return kept

In [53]:
threshold_soft_hit_rate, threshold_soft_hit_by_category, threshold_soft_df = compute_hit_rate_reranked(
    positive_sample, index_hybrid, retrieve_fn=retrieve_scoped_reranked_threshold_soft
)
print(f"Retrieval avec filtrage seuil doux: {threshold_soft_hit_rate:.3f}")

Retrieval avec filtrage seuil doux: 0.693

In [54]:
comparison_hit_v2 = pd.DataFrame({
    "sans_filtrage_0.746": adaptive_hit_by_category,
    "seuil_strict_0.663": threshold_hit_by_category,
    "seuil_doux_0.693": threshold_soft_hit_by_category,
})
comparison_hit_v2["delta_doux_vs_sans"] = comparison_hit_v2["seuil_doux_0.693"] - comparison_hit_v2["sans_filtrage_0.746"]
print(comparison_hit_v2.sort_values("delta_doux_vs_sans").to_string())

                                    sans_filtrage_0.746  seuil_strict_0.663  seuil_doux_0.693  delta_doux_vs_sans
category
Non-Compete                                         1.0                 0.4               0.4                -0.6
Price Restrictions                                  1.0                 0.4               0.6                -0.4
Warranty Duration                                   0.8                 0.6               0.6                -0.2
Volume Restriction                                  0.6                 0.4               0.4                -0.2
Audit Rights                                        1.0                 0.8               0.8                -0.2
Rofr/Rofo/Rofn                                      0.6                 0.2               0.4                -0.2
Ip Ownership Assignment                             0.6                 0.4               0.4                -0.2
No-Solicit Of Customers                             0.6                 0.4               0.4                -0.2
No-Solicit Of Employees                             1.0                 1.0               1.0                 0.0
Unlimited/All-You-Can-Eat-License                   0.6                 0.6               0.6                 0.0
Non-Disparagement                                   0.6                 0.6               0.6                 0.0
Non-Transferable License                            0.8                 0.6               0.8                 0.0
Notice Period To Terminate Renewal                  0.8                 0.8               0.8                 0.0
Third Party Beneficiary                             1.0                 1.0               1.0                 0.0
Uncapped Liability                                  1.0                 1.0               1.0                 0.0
Renewal Term                                        1.0                 1.0               1.0                 0.0
Revenue/Profit Sharing                              0.2                 0.0               0.2                 0.0
Source Code Escrow                                  0.8                 0.8               0.8                 0.0
Termination For Convenience                         1.0                 0.8               1.0                 0.0
Parties                                             1.0                 1.0               1.0                 0.0
Post-Termination Services                           0.6                 0.6               0.6                 0.0
Affiliate License-Licensee                          0.8                 0.8               0.8                 0.0
Liquidated Damages                                  0.4                 0.4               0.4                 0.0
Affiliate License-Licensor                          0.8                 0.8               0.8                 0.0
Agreement Date                                      0.8                 0.8               0.8                 0.0
Anti-Assignment                                     1.0                 1.0               1.0                 0.0
Cap On Liability                                    0.8                 0.8               0.8                 0.0
Change Of Control                                   1.0                 1.0               1.0                 0.0
Competitive Restriction Exception                   0.4                 0.4               0.4                 0.0
Covenant Not To Sue                                 0.4                 0.4               0.4                 0.0
Most Favored Nation                                 0.2                 0.2               0.2                 0.0
Document Name                                       1.0                 1.0               1.0                 0.0
Exclusivity                                         0.4                 0.2               0.4                 0.0
Expiration Date                                     0.8                 0.8               0.8                 0.0
Governing Law                                       1.0                 1.0               1.0                 0.0
Insurance                                           0.8                 0.8               0.8                 0.0
Irrevocable Or Perpetual License                    0.8                 0.8               0.8                 0.0
Joint Ip Ownership                                  0.8                 0.8               0.8                 0.0
License Grant                                       1.0                 1.0               1.0                 0.0
Effective Date                                      0.8                 0.8               0.8                 0.0
Minimum Commitment                                  0.0                 0.0               0.0                 0.0

In [55]:
def generate_answer(title, question, category):
    retrieved = retrieve_scoped_reranked_threshold_soft(title, question, category, index_hybrid)
    contexts = [r["text"] for r in retrieved]
    context_str = "\n\n".join(contexts)
    prompt = qa_prompt_template.format(context_str=context_str, query_str=question)
    response = llm.complete(prompt)
    return str(response), contexts

In [57]:
checkpoint["threshold_hit_rate"] = threshold_hit_rate
checkpoint["threshold_hit_by_category"] = threshold_hit_by_category
checkpoint["threshold_df"] = threshold_df
checkpoint["threshold_soft_hit_rate"] = threshold_soft_hit_rate
checkpoint["threshold_soft_hit_by_category"] = threshold_soft_hit_by_category
checkpoint["threshold_soft_df"] = threshold_soft_df
checkpoint["POSITION_THRESHOLDS"] = POSITION_THRESHOLDS
checkpoint["POSITION_THRESHOLDS_SOFT"] = POSITION_THRESHOLDS_SOFT

with open("../artifacts/baseline_v2_checkpoint.pkl", "wb") as f:
    pickle.dump(checkpoint, f)

print("Checkpoint mis a jour avant redemarrage.")

Checkpoint mis a jour avant redemarrage.

In [1]:
import pickle
with open("../artifacts/baseline_v2_checkpoint.pkl", "rb") as f:
    checkpoint = pickle.load(f)
for key, value in checkpoint.items():
    globals()[key] = value
print("Checkpoint recharge:", list(checkpoint.keys()))

Checkpoint recharge: ['baseline_hit_rate', 'baseline_hit_vy_category', 'baseline_df', 'bge_large_hit_rate', 'bge_large_hit_vy_category', 'bge_large_df', 'nomic_hit_rate', 'nomic_hit_vy_category', 'nomic_df', 'e5_hit_rate', 'e5_hit_by_category', 'e5_df', 'hybrid_hit_rate', 'hybrid_hit_by_category', 'hybrid_df', 'reranked_hit_rate', 'reranked_hit_by_category', 'reranked_df', 'merged', 'positive_sample', 'negative_sample', 'category_to_tier', 'reranked_large_short_hit_rate', 'reranked_large_short_hit_by_category', 'reranked_large_short_df', 'positive_large_short_scores_df', 'negative_large_short_scores_df', 'adaptive_hit_rate', 'adaptive_hit_by_category', 'adaptive_df', 'sentence_window_hit_rate', 'sentence_window6_hit_rate', 'recursive_hit_rate', 'recursive_hit_by_category', 'recursive_df', 'sentence_window_hit_by_category', 'sentence_window_df', 'sentence_window6_hit_by_category', 'sentence_window6_df', 'threshold_hit_rate', 'threshold_hit_by_category', 'threshold_df', 'threshold_soft_hit_rate', 'threshold_soft_hit_by_category', 'threshold_soft_df', 'POSITION_THRESHOLDS', 'POSITION_THRESHOLDS_SOFT']

In [3]:
from datasets import load_dataset, concatenate_datasets

dataset = load_dataset("theatticusproject/cuad-qa", revision="refs/convert/parquet")
train_data = dataset["train"]
test_data = dataset["test"]
print(len(train_data))
print(len(test_data))

22450
4182

In [4]:
full_data = concatenate_datasets([train_data, test_data])

In [5]:
seen_titles = set()
unique_contracts = []

for row in full_data:
    if row["title"] not in seen_titles:
        seen_titles.add(row["title"])
        unique_contracts.append({
            "title": row["title"],
            "context": row["context"]
        })
print(f"Number of unique contracts: {len(unique_contracts)}")

Number of unique contracts: 510

In [6]:
import re

def clean_contract_text(text: str) -> str:

    text = re.sub(r"[ \t]{2,}", " ", text)

    text = re.sub(r"\n{3,}", "\n\n", text)

    text = "\n".join(line.strip() for line in text.split('\n'))

    return text.strip()

In [7]:
for c in unique_contracts:
    c["clean_context"] = clean_contract_text(c["context"])

In [8]:
for item in positive_sample:
    item["ground_truth_clean"] = [clean_contract_text(a) for a in item["ground_truth"]]

In [9]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("BAAI/bge-small-en-v1.5")

In [10]:
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core import Document
from collections import defaultdict

CHUNK_SIZE = 512
CHUNK_OVERLAP = 50

Splitter = SentenceSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    tokenizer=tokenizer.encode
)

documents = [
    Document(
        text=c["clean_context"], metadata={"title": c["title"]})
        for c in unique_contracts
]

nodes = Splitter.get_nodes_from_documents(documents)

# chunk index for each contract
counters = defaultdict(int)
for n in nodes:
    title = n.metadata["title"]
    n.metadata["chunk_index"] = counters[title]
    counters[title] += 1

print(f"Number of contracts : {len(documents)}")
print(f"Number of chunks: {len(nodes)}")
print(f"Average chunks per contract: {len(nodes)/len(documents):.1f}")

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (7558 > 512). Running this sequence through the model will result in indexing errors

Number of contracts : 510
Number of chunks: 14230
Average chunks per contract: 27.9

In [11]:
from llama_index.core.postprocessor import SentenceTransformerRerank
reranker = SentenceTransformerRerank(model="BAAI/bge-reranker-large", top_n=3)

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 5274.32it/s]

In [12]:
from llama_index.core.vector_stores import MetadataFilters, ExactMatchFilter
import re

def strip_boilerplate(question):
    match = re.search(r'"([^"]+)"', question)
    category_quoted = match.group(0) if match else ""
    details = question.split("Details: ", 1)[1] if "Details: " in question else ""
    return f"{category_quoted}. {details}".strip()

In [13]:
POSITION_THRESHOLDS_SOFT = {2: 0.00029, 3: 0.00020, 4: 0.00012, 5: 0.00011}

def retrieve_scoped_reranked_threshold_soft(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.get_content(), "score": None} for n in selected]

    if tier == 3:
        retrieve_top_k = 15
        sparse_top_k = 15
        rerank_top_n = 5

    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    kept = []
    for position, n in enumerate(reranked_nodes, start=1):
        if position == 1:
            kept.append({"text": n.get_content(), "score": n.score})
        elif n.score is not None and n.score >= POSITION_THRESHOLDS_SOFT.get(position, float("inf")):
            kept.append({"text": n.get_content(), "score": n.score})

    return kept

In [14]:
from llama_index.core import PromptTemplate

qa_prompt_template = PromptTemplate(
    "Context information from the contract is below.\n"
    "---------------------\n"
    "{context_str}\n"
    "---------------------\n"
    "You are a contract review assistant analyzing one contract.\n"
    "Follow these steps:\n"
    "1. Decide whether the context above contains information relevant to the question. "
    "A relevant answer can be a full sentence, a clause, a heading, a title, a date, or a list of names "
    "— not only complete grammatical sentences.\n"
    "2. Do not treat a bare section heading or title (with no accompanying clause text) as an answer just "
    "because it resembles the category name in the question. However, if the context contains actual clause "
    "text — obligations, rights, restrictions, or definitions — that addresses what the question's \"Details\" "
    "describes, that IS valid evidence: quote it normally. Only treat something as \"not present\" when there "
    "is no clause text addressing the details, not merely because a heading happens to be present.\n"
    "3. If the question asks about the Document Name (the name/title of the contract), the answer is "
    "typically a short heading (2-6 words, often in ALL CAPS) located at the very beginning of the context "
    "— either the very first line, or the line immediately following an \"Exhibit X.X\" reference or a "
    "confidentiality/legal notice. Answer with ONLY this short title, do not include the surrounding "
    "paragraphs, recitals, or signature blocks.\n"
    "4. If the question asks about a specific date (such as Agreement Date or Effective Date), answer "
    "ONLY with the explicit date mentioned in a sentence that clearly labels it as such (e.g. \"the Effective Date\", "
    "\"dated as of\"). Do not infer a date from unrelated clauses such as renewal terms, option expirations, "
    "or other unrelated dates.\n"
    "5. Otherwise, if relevant information exists, respond with ONLY the exact text from the context that "
    "answers the question. Quote it directly. Do not paraphrase, do not add explanations or recommendations.\n"
    "6. If nothing in the context is relevant to the question, respond with EXACTLY the following sentence, "
    "word for word, with no rephrasing or additions: \"This clause is not present in this contract.\"\n"
    "Never combine both — give exactly one of the two response types above (step 5 or step 6), never a mix.\n"
    "Question: {query_str}\n"
    "Answer: "
)


from llama_index.llms.ollama import Ollama
llm = Ollama(model="llama3.2:3b", request_timeout=180, temperature=0.0)

In [15]:
def generate_answer(title, question, category):
    retrieved = retrieve_scoped_reranked_threshold_soft(title, question, category, index_hybrid)
    contexts = [r["text"] for r in retrieved]
    context_str = "\n\n".join(contexts)
    prompt = qa_prompt_template.format(context_str=context_str, query_str=question)
    response = llm.complete(prompt)
    return str(response), contexts

In [16]:
import os
import json
from tqdm import tqdm

def run_generation(sample, is_positive, output_path):
    if os.path.exists(output_path):
        with open(output_path) as f:
            results = json.load(f)
        done_keys = {(r["title"], r["question"]) for r in results}
        remaining = [item for item in sample if (item["title"], item["question"]) not in done_keys]
        print(f"Reprise : {len(results)} deja faits, {len(remaining)} restants")
    else:
        results = []
        remaining = sample

    for item in tqdm(remaining):
        try:
            answer, contexts = generate_answer(item["title"], item["question"], item["category"])
        except Exception as e:
            answer = f"[ERROR: {type(e).__name__}: {e}]"
            contexts = []

        result = {
            "title": item["title"], "category": item["category"],
            "tier": category_to_tier.get(item["category"], 2),
            "question": item["question"], "answer": answer,
            "contexts": contexts, "is_positive": is_positive,
        }
        result["ground_truth"] = " ".join(item["ground_truth_clean"]) if is_positive else "This clause is not present in this contract."
        results.append(result)
        with open(output_path, "w") as f:
            json.dump(results, f, indent=2)
    return results

In [2]:
from qdrant_client import QdrantClient
from llama_index.embeddings.ollama import OllamaEmbedding
from llama_index.vector_stores.qdrant import QdrantVectorStore
from llama_index.core import VectorStoreIndex

client = QdrantClient(path="../artifacts/qdrant_storage")
nomic_embed = OllamaEmbedding(model_name="nomic-embed-text")

vector_store_hybrid = QdrantVectorStore(
    collection_name="cuad_nomic_bm25_hybrid",
    client=client,
    enable_hybrid=True,
    fastembed_sparse_model="Qdrant/bm25",
)
index_hybrid = VectorStoreIndex.from_vector_store(vector_store_hybrid, embed_model=nomic_embed)

/Users/aitbellalhamza/Desktop/RAG-for-contract-understanding-CUAD/.cuad-venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/var/folders/2d/1h410ps12gn5kw05_3p23qpc0000gn/T/ipykernel_20471/1507995236.py:6: UserWarning: Local mode is not recommended for collections with more than 20,000 points. Collection <cuad_sentence_widow_hybrid> contains 50675 points. Consider using Qdrant in Docker or Qdrant Cloud for better performance with large datasets.
  client = QdrantClient(path="../artifacts/qdrant_storage")
/var/folders/2d/1h410ps12gn5kw05_3p23qpc0000gn/T/ipykernel_20471/1507995236.py:6: UserWarning: Local mode is not recommended for collections with more than 20,000 points. Collection <cuad_sentence_window6_hybrid> contains 50675 points. Consider using Qdrant in Docker or Qdrant Cloud for better performance with large datasets.
  client = QdrantClient(path="../artifacts/qdrant_storage")

In [17]:
positive_results_v2_threshold = run_generation(
    positive_sample, is_positive=True, output_path="../artifacts/positive_results_v2_threshold.json"
)
print(f"saved {len(positive_results_v2_threshold)} positive results.")

Reprise : 41 deja faits, 164 restants

  7%|▋         | 11/164 [04:39<1:19:27, 31.16s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
 16%|█▌        | 26/164 [12:04<1:06:44, 29.02s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
100%|██████████| 164/164 [1:18:40<00:00, 28.78s/it]

saved 205 positive results.

In [18]:
positive_results_v2_threshold_clean = [r for r in positive_results_v2_threshold if not r["answer"].startswith("[ERROR")]
print(f"{len(positive_results_v2_threshold_clean)} usable after removing errors")

ragas_data = [
    {
        "user_input": item["question"],
        "response": item["answer"],
        "retrieved_contexts": item["contexts"],
        "reference": item["ground_truth"],
    }
    for item in positive_results_v2_threshold_clean
]

203 usable after removing errors

In [19]:
from dotenv import load_dotenv
load_dotenv(override=True)

from langchain_anthropic import ChatAnthropic
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LlamaIndexEmbeddingsWrapper

class ChatAnthropicNoTemp(ChatAnthropic):
    def __setattr__(self, name, value):
        if name == "temperature":
            return
        super().__setattr__(name, value)

claude_llm = ChatAnthropicNoTemp(model="claude-haiku-4-5", max_tokens=4096)
ragas_llm_claude = LangchainLLMWrapper(claude_llm)
ragas_embeddings = LlamaIndexEmbeddingsWrapper(nomic_embed)

from ragas.metrics import faithfulness, answer_correctness, answer_relevancy, context_precision, context_recall
from ragas.run_config import RunConfig

metrics = [faithfulness, answer_relevancy, context_precision, context_recall, answer_correctness]
run_config_claude = RunConfig(timeout=180, max_workers=4)

In [20]:
from ragas import EvaluationDataset, evaluate
import json, time, os

BATCH_SIZE = 20
output_path = "../artifacts/ragas_scores_v2_threshold.json"

if os.path.exists(output_path):
    with open(output_path) as f:
        all_scores = json.load(f)
else:
    all_scores = []

start_index = len(all_scores)
n_batches = (len(ragas_data) - 1) // BATCH_SIZE + 1

for i in range(start_index, len(ragas_data), BATCH_SIZE):
    batch = ragas_data[i : i + BATCH_SIZE]
    batch_dataset = EvaluationDataset.from_list(batch)
    print(f"batch {i // BATCH_SIZE + 1}/{n_batches} ({len(batch)} examples)...")

    result = evaluate(dataset=batch_dataset, metrics=metrics, llm=ragas_llm_claude,
                       embeddings=ragas_embeddings, run_config=run_config_claude)

    all_scores.extend(result.to_pandas().to_dict(orient="records"))
    with open(output_path, "w") as f:
        json.dump(all_scores, f, indent=2)
    print(f" -> saved ({len(all_scores)}/{len(ragas_data)})")

batch 1/11 (20 examples)...

Evaluating: 100%|██████████| 100/100 [01:50<00:00,  1.10s/it]

 -> saved (20/203)
batch 2/11 (20 examples)...

Evaluating: 100%|██████████| 100/100 [02:34<00:00,  1.55s/it]

 -> saved (40/203)
batch 3/11 (20 examples)...

Evaluating: 100%|██████████| 100/100 [03:40<00:00,  2.21s/it]

 -> saved (60/203)
batch 4/11 (20 examples)...

Evaluating: 100%|██████████| 100/100 [04:01<00:00,  2.42s/it]

 -> saved (80/203)
batch 5/11 (20 examples)...

Evaluating: 100%|██████████| 100/100 [03:47<00:00,  2.27s/it]

 -> saved (100/203)
batch 6/11 (20 examples)...

Evaluating:  31%|███       | 31/100 [01:12<04:10,  3.63s/it]Exception raised in Job[20]: LLMDidNotFinishException(The LLM generation was not completed. Please increase the max_tokens and try again.)
Evaluating: 100%|██████████| 100/100 [03:48<00:00,  2.28s/it]

 -> saved (120/203)
batch 7/11 (20 examples)...

Evaluating: 100%|██████████| 100/100 [03:24<00:00,  2.04s/it]

 -> saved (140/203)
batch 8/11 (20 examples)...

Evaluating: 100%|██████████| 100/100 [03:12<00:00,  1.92s/it]

 -> saved (160/203)
batch 9/11 (20 examples)...

Evaluating: 100%|██████████| 100/100 [03:21<00:00,  2.02s/it]

 -> saved (180/203)
batch 10/11 (20 examples)...

Evaluating:  91%|█████████ | 91/100 [03:42<00:34,  3.80s/it]Exception raised in Job[79]: LLMDidNotFinishException(The LLM generation was not completed. Please increase the max_tokens and try again.)
Evaluating: 100%|██████████| 100/100 [04:13<00:00,  2.53s/it]

 -> saved (200/203)
batch 11/11 (3 examples)...

Evaluating: 100%|██████████| 15/15 [00:34<00:00,  2.33s/it]

 -> saved (203/203)

In [21]:
import pandas as pd

for score_row, meta_row in zip(all_scores, positive_results_v2_threshold_clean):
    score_row["category"] = meta_row["category"]

df_scores_v2t = pd.DataFrame(all_scores)
metric_cols = ["faithfulness", "answer_relevancy", "context_precision", "context_recall", "answer_correctness"]

summary_v2_threshold = df_scores_v2t[metric_cols].mean().to_frame(name="moyenne_v2_seuil_doux")
print(summary_v2_threshold)

summary_v2_threshold.to_csv("../artifacts/ragas_scores_v2_threshold_summary_global.csv")

                    moyenne_v2_seuil_doux
faithfulness                     0.767345
answer_relevancy                 0.578034
context_precision                0.377709
context_recall                   0.433623
answer_correctness               0.391249

In [22]:
def generate_answer(title, question, category):
    retrieved = retrieve_scoped_reranked_adaptive_topk(title, question, category, index_hybrid)
    contexts = [r["text"] for r in retrieved]
    context_str = "\n\n".join(contexts)
    prompt = qa_prompt_template.format(context_str=context_str, query_str=question)
    response = llm.complete(prompt)
    return str(response), contexts

In [25]:
def retrieve_scoped_reranked_adaptive_topk(title, question, category, index, retrieve_top_k=10, sparse_top_k=10, rerank_top_n=3):
    tier = category_to_tier.get(category, 2)
    contract_nodes = [n for n in nodes if n.metadata["title"] == title]

    if tier == 1:
        contract_nodes = sorted(contract_nodes, key=lambda n: n.metadata["chunk_index"])
        selected = contract_nodes[:1]
        return [{"text": n.get_content(), "score": None} for n in selected]

    if tier == 3:
        retrieve_top_k = 15
        sparse_top_k = 15
        rerank_top_n = 5

    filtered_retriever = index.as_retriever(
        similarity_top_k=retrieve_top_k,
        sparse_top_k=sparse_top_k,
        vector_store_query_mode="hybrid",
        filters=MetadataFilters(filters=[ExactMatchFilter(key="title", value=title)])
    )
    retrieved_nodes = filtered_retriever.retrieve(question)

    reranker.top_n = rerank_top_n
    short_question = strip_boilerplate(question)
    reranked_nodes = reranker.postprocess_nodes(retrieved_nodes, query_str=short_question)

    return [{"text": n.get_content(), "score": n.score} for n in reranked_nodes]

In [26]:
negative_results_v2 = run_generation(
    negative_sample, is_positive=False, output_path="../artifacts/negative_results_v2.json"
)
print(f"saved {len(negative_results_v2)} negative results.")

 36%|███▋      | 43/118 [22:19<40:05, 32.07s/it]  Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
 53%|█████▎    | 62/118 [32:20<23:10, 24.83s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
 58%|█████▊    | 69/118 [34:57<18:29, 22.63s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
 63%|██████▎   | 74/118 [36:44<17:02, 23.24s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
 70%|███████   | 83/118 [40:07<12:49, 22.00s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
 74%|███████▎  | 87/118 [41:47<12:49, 24.84s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
 75%|███████▌  | 89/118 [42:23<10:21, 21.44s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
 81%|████████▏ | 96/118 [45:13<08:08, 22.22s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
 89%|████████▉ | 105/118 [48:27<04:08, 19.12s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
 97%|█████████▋| 114/118 [53:20<02:51, 42.98s/it]Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG13XFamilyCommandBuffer: 0xa9fbc0000>
    label = <none>
    device = <AGXG13XDevice: 0x10183a6f0>
        name = Apple M1 Pro
    commandQueue = <AGXG13XFamilyCommandQueue: 0x10183cbb0>
        label = <none>
        device = <AGXG13XDevice: 0x10183a6f0>
            name = Apple M1 Pro
    retainedReferences = 1
100%|██████████| 118/118 [54:41<00:00, 27.81s/it]

saved 118 negative results.

In [27]:
from collections import Counter

ABSENCE_PHRASES = [
    "not present", "not specified", "not mentioned", "does not contain",
    "no clause", "not applicable", "not included", "not found", "n/a", "absent"
]

def classify_negative(answer):
    if answer.startswith("[ERROR"):
        return "error"
    answer_lower = answer.lower()
    if any(phrase in answer_lower for phrase in ABSENCE_PHRASES):
        return "true negative"
    return "false positive"

for item in negative_results_v2:
    item["classification"] = classify_negative(item["answer"])

counts_v2 = Counter(item["classification"] for item in negative_results_v2)
print(counts_v2)

total_classifiable_v2 = counts_v2["true negative"] + counts_v2["false positive"]
fp_rate_v2 = counts_v2["false positive"] / total_classifiable_v2 * 100
print(f"False positive rate v2: {fp_rate_v2:.1f}% ({counts_v2['false positive']}/{total_classifiable_v2})")

Counter({'false positive': 78, 'true negative': 40})
False positive rate v2: 66.1% (78/118)